using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Localization;
using Microsoft.EntityFrameworkCore;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RentACar.DataAccess
{
    public class RentACarDbContext:IdentityDbContext<IdentityUser>
    {
        public RentACarDbContext(DbContextOptions<RentACarDbContext> options) : base(options) { }   
        public DbSet<Car> Cars { get; set; }
        public DbSet<CType> Types { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<CarFeature> CarsFeatures { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<ClassOfCar> ClassOfCars { get; set; }
        public DbSet<Customer>Customers { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<CarCompany>CarCompanies { get; set; }
      
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {



            modelBuilder.Entity<Reservation>().HasOne(r => r.Customer).WithMany(c => c.Reservations).HasForeignKey(r => r.CustomerId).OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<Customer>().HasOne(c => c.User).WithOne().HasForeignKey<Customer>(c => c.UserId).OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<CarCompany>().HasOne(c => c.User).WithOne(u => u.CarCompany).HasForeignKey<CarCompany>(c => c.UserId).OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<ClassOfCar>().HasData(
new ClassOfCar { Id = 1, Name = "Economy" },
new ClassOfCar { Id = 2, Name = "Luxury" },
new ClassOfCar { Id = 3, Name = "Sport" },
new ClassOfCar { Id = 4, Name = "Business" },
new ClassOfCar { Id = 5, Name = "Electric" },
new ClassOfCar { Id = 6, Name = "Standard" },
new ClassOfCar { Id = 7, Name = "Retro" }

);
            modelBuilder.Entity<CType>().HasData(
                new CType { Id = 1, Name = "Sedan", SeatCapacity = 4 },
                new CType { Id = 2, Name = "SUV", SeatCapacity = 5 },
                new CType { Id = 3, Name = "SUV", SeatCapacity = 7 },
                new CType { Id = 4, Name = "Hatchback", SeatCapacity = 4 },
                new CType { Id = 5, Name = "Hatchback", SeatCapacity = 2 },
                new CType { Id = 6, Name = "Coupe", SeatCapacity = 2 },
                new CType { Id = 7, Name = "Coupe", SeatCapacity = 4 },
                new CType { Id = 8, Name = "Grand Coupe", SeatCapacity = 4 },
                new CType { Id = 9, Name = "Minivan", SeatCapacity = 7 },
                new CType { Id = 10, Name = "Pickup", SeatCapacity = 2 },
                new CType { Id = 11, Name = "Pickup", SeatCapacity = 4 },
                new CType { Id = 12, Name = "Wagon", SeatCapacity = 5 }

            );
            modelBuilder.Entity<Car>().HasData(
new Car { Id = 1, Brand = "Toyota", Model = "Corolla", Gearbox = "Automatic", Year = 2021, PricePerDay = 80, PricePerWeek = 450, MileageLimitForDay = 150, MileageLimitForWeek = 1000, AdditionalMileageCharge = 0.2, EngineCapacity = 1.6, Color = "White", Available = true, Description = "Compact and fuel-efficient", ClassOfCarId = 1, DriveTrain = "Front", HorsePower = 122, ZeroToHundred = 10.8, TopSpeed = 185, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 1 },
new Car { Id = 2, Brand = "Honda", Model = "Civic", Gearbox = "Manual", Year = 2022, PricePerDay = 140, PricePerWeek = 600, MileageLimitForDay = 200, MileageLimitForWeek = 1200, AdditionalMileageCharge = 0.25, EngineCapacity = 1.5, Color = "Black", Available = true, Description = "Sporty and reliable", ClassOfCarId = 6, DriveTrain = "Front", HorsePower = 205, ZeroToHundred = 7.3, TopSpeed = 170, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 1 },
new Car { Id = 3, Brand = "Ford", Model = "Mustang", Gearbox = "Automatic", Year = 2020, PricePerDay = 200, PricePerWeek = 910, MileageLimitForDay = 250, MileageLimitForWeek = 1500, AdditionalMileageCharge = 0.22, EngineCapacity = 2.3, Color = "Dark Gray", Available = true, Description = "Comfortable and stylish", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 317, ZeroToHundred = 5.8, TopSpeed = 250, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 6, IsConvertable = true },
new Car { Id = 4, Brand = "BMW", Model = "420", Gearbox = "Automatic", Year = 2022, PricePerDay = 250, PricePerWeek = 1000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 0.5, EngineCapacity = 2.0, Color = "Gray", Available = true, Description = "Luxury and performance", ClassOfCarId = 2, DriveTrain = "Rear", HorsePower = 190, ZeroToHundred = 7.1, TopSpeed = 240, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 6, IsConvertable = true },
new Car { Id = 5, Brand = "Mercedes-Benz", Model = "C-Class", Gearbox = "Automatic", Year = 2021, PricePerDay = 210, PricePerWeek = 850, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 0.55, EngineCapacity = 3.0, Color = "Red", Available = true, Description = "Premium luxury", ClassOfCarId = 2, DriveTrain = "Rear", HorsePower = 258, ZeroToHundred = 6.2, TopSpeed = 250, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 6, IsConvertable = true },
new Car { Id = 6, Brand = "Audi", Model = "R8 Spyder", Gearbox = "Automatic", Year = 2021, PricePerDay = 750, PricePerWeek = 6400, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 1.0, EngineCapacity = 5.2, Color = "Green", Available = true, Description = "High-performance sports car", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 570, ZeroToHundred = 3.8, TopSpeed = 327, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5, IsConvertable = true },
new Car { Id = 7, Brand = "Lamborghini", Model = "Huracan", Gearbox = "Automatic", Year = 2023, PricePerDay = 1700, PricePerWeek = 9000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 1.5, EngineCapacity = 5.2, Color = "Black", Available = true, Description = "Exotic sports car", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 640, ZeroToHundred = 3.0, TopSpeed = 310, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5, IsConvertable = true },
new Car { Id = 8, Brand = "Porsche", Model = "911 GT3", Gearbox = "Automatic", Year = 2023, PricePerDay = 1400, PricePerWeek = 8400, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 1.3, EngineCapacity = 3.0, Color = "Silver", Available = true, Description = "Luxury sports car", ClassOfCarId = 3, DriveTrain = "Full Wheels", HorsePower = 450, ZeroToHundred = 3.8, TopSpeed = 304, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5 },
new Car { Id = 9, Brand = "Tesla", Model = "Model S Plaid", Gearbox = "Automatic", Year = 2023, PricePerDay = 350, PricePerWeek = 2100, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 1.0, EngineCapacity = 0.0, Color = "White", Available = true, Description = "Electric luxury sedan", ClassOfCarId = 5, DriveTrain = "Rear", HorsePower = 1020, ZeroToHundred = 2.1, TopSpeed = 322, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 1 },
new Car { Id = 10, Brand = "Ferrari", Model = "F8 Spider", Gearbox = "Automatic", Year = 2022, PricePerDay = 2300, PricePerWeek = 10000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 2.0, EngineCapacity = 3.9, Color = "Red", Available = true, Description = "Iconic Italian sports car", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 720, ZeroToHundred = 2.9, TopSpeed = 340, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5, IsConvertable = true },
new Car { Id = 11, Brand = "Rolls-Royce", Model = "Phantom", Gearbox = "Automatic", Year = 2021, PricePerDay = 1000, PricePerWeek = 7000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.0, EngineCapacity = 6.8, Color = "Black", Available = true, Description = "Ultimate luxury car", ClassOfCarId = 4, DriveTrain = "Rear", HorsePower = 571, ZeroToHundred = 5.4, TopSpeed = 250, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 1 },
new Car { Id = 12, Brand = "Bentley", Model = "Continental GT-GTC", Gearbox = "Automatic", Year = 2023, PricePerDay = 1300, PricePerWeek = 7600, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.5, EngineCapacity = 6.0, Color = "Black", Available = true, Description = "Grand luxury tourer", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 659, ZeroToHundred = 3.7, TopSpeed = 335, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 6, IsConvertable = true },
new Car { Id = 13, Brand = "McLaren", Model = "720S", Gearbox = "Automatic", Year = 2023, PricePerDay = 1700, PricePerWeek = 8000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 2.0, EngineCapacity = 4.0, Color = "Blue", Available = true, Description = "Exquisite British engineering", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 720, ZeroToHundred = 2.9, TopSpeed = 341, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5 },
new Car { Id = 14, Brand = "Aston Martin", Model = "DBX", Gearbox = "Automatic", Year = 2023, PricePerDay = 600, PricePerWeek = 3600, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.0, EngineCapacity = 4.0, Color = "Black", Available = true, Description = "Luxury British SUV", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 550, ZeroToHundred = 4.5, TopSpeed = 291, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 2 },
new Car { Id = 15, Brand = "Lexus", Model = "LX", Gearbox = "Automatic", Year = 2023, PricePerDay = 500, PricePerWeek = 3000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.5, Color = "Silver", Available = true, Description = "Sophisticated luxury SUV", ClassOfCarId = 2, DriveTrain = "Full Wheels", HorsePower = 415, ZeroToHundred = 6.8, TopSpeed = 210, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 3 },
new Car { Id = 16, Brand = "Mercedes-Benz", Model = "AMG GT", Gearbox = "Automatic", Year = 2022, PricePerDay = 2500, PricePerWeek = 1100, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 2.2, EngineCapacity = 4.0, Color = "Orange", Available = true, Description = "German engineering excellence", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 730, ZeroToHundred = 3.2, TopSpeed = 322, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5 },
new Car { Id = 17, Brand = "Audi", Model = "Q8", Gearbox = "Automatic", Year = 2021, PricePerDay = 400, PricePerWeek = 2300, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.0, EngineCapacity = 3.0, Color = "Orange", Available = true, Description = "Luxury SUV", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 340, ZeroToHundred = 5.9, TopSpeed = 250, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 2 },
new Car { Id = 18, Brand = "BMW", Model = "M4", Gearbox = "Automatic", Year = 2023, PricePerDay = 700, PricePerWeek = 4000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.5, EngineCapacity = 3.0, Color = "Yellow", Available = true, Description = "Sporty and agile", ClassOfCarId = 3, DriveTrain = "Full Wheels", HorsePower = 510, ZeroToHundred = 3.7, TopSpeed = 250, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 6, IsConvertable = true },
new Car { Id = 19, Brand = "Toyota", Model = "Camry", Gearbox = "Automatic", Year = 2021, PricePerDay = 130, PricePerWeek = 670, MileageLimitForDay = 200, MileageLimitForWeek = 1200, AdditionalMileageCharge = 0.25, EngineCapacity = 2.5, Color = "Red", Available = true, Description = "Dependable sedan", ClassOfCarId = 6, DriveTrain = "Rear", HorsePower = 182, ZeroToHundred = 9.9, TopSpeed = 210, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 1 },
new Car { Id = 20, Brand = "Tesla", Model = "Cybertruck", Gearbox = "Automatic", Year = 2024, PricePerDay = 2000, PricePerWeek = 12000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 0.0, Color = "Black", Available = true, Description = "Sophisticated luxury SUV", ClassOfCarId = 5, DriveTrain = "Full Wheels", HorsePower = 845, ZeroToHundred = 2.7, TopSpeed = 210, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 11 },
new Car { Id = 21, Brand = "Land Rover", Model = "Range Rover", Gearbox = "Automatic", Year = 2023, PricePerDay = 1200, PricePerWeek = 7000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.0, Color = "Black", Available = true, Description = "Sophisticated luxury SUV", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 360, ZeroToHundred = 6.9, TopSpeed = 209, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 2 },
new Car { Id = 22, Brand = "Toyota", Model = "Supra", Gearbox = "Automatic", Year = 2022, PricePerDay = 220, PricePerWeek = 1100, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.0, Color = "White", Available = true, Description = "Sporty and agile", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 340, ZeroToHundred = 4.4, TopSpeed = 262, CarCompanyId = 1, Pending = false, CreatedAt = DateTime.ParseExact("2025_01_14_14_30_45", "yyyy_MM_dd_HH_mm_ss", CultureInfo.InvariantCulture), CTypeId = 5 }
);


            modelBuilder.Entity<Feature>().HasData(
      new Feature { Id = 1, NameOfFeatures = "Air Conditioning" },
      new Feature { Id = 2, NameOfFeatures = "Heated Seats" },
      new Feature { Id = 3, NameOfFeatures = "Bluetooth Connectivity" },
      new Feature { Id = 4, NameOfFeatures = "Navigation System" },
      new Feature { Id = 5, NameOfFeatures = "Cruise Control" },
      new Feature { Id = 6, NameOfFeatures = "Rearview Camera" },
      new Feature { Id = 7, NameOfFeatures = "Lane Departure Warning" },
      new Feature { Id = 8, NameOfFeatures = "Adaptive Headlights" },
      new Feature { Id = 9, NameOfFeatures = "Blind Spot Detection" },
      new Feature { Id = 10, NameOfFeatures = "Automatic Parking" },
      new Feature { Id = 11, NameOfFeatures = "Push-Button Start" },
      new Feature { Id = 12, NameOfFeatures = "Wireless Charging" },
      new Feature { Id = 13, NameOfFeatures = "Panoramic Sunroof" },
      new Feature { Id = 14, NameOfFeatures = "Power Adjustable Seats" },
      new Feature { Id = 15, NameOfFeatures = "Backup Sensors" },
      new Feature { Id = 16, NameOfFeatures = "Heated Steering Wheel" },
      new Feature { Id = 17, NameOfFeatures = "Keyless Entry" },
      new Feature { Id = 18, NameOfFeatures = "Surround-View Camera" },
      new Feature { Id = 19, NameOfFeatures = "Remote Start" },
      new Feature { Id = 20, NameOfFeatures = "Apple CarPlay" },
      new Feature { Id = 21, NameOfFeatures = "Android Auto" },
      new Feature { Id = 22, NameOfFeatures = "Rear Cross Traffic Alert" },
      new Feature { Id = 23, NameOfFeatures = "Adaptive Cruise Control" },
      new Feature { Id = 24, NameOfFeatures = "Heads-Up Display (HUD)" },
      new Feature { Id = 25, NameOfFeatures = "Ambient Lighting" },
      new Feature { Id = 26, NameOfFeatures = "Wireless Apple CarPlay" },
      new Feature { Id = 27, NameOfFeatures = "Power Tailgate" },
      new Feature { Id = 28, NameOfFeatures = "Automatic Emergency Braking" },
      new Feature { Id = 29, NameOfFeatures = "Traffic Sign Recognition" },
      new Feature { Id = 30, NameOfFeatures = "Rain-Sensing Wipers" },
      new Feature { Id = 31, NameOfFeatures = "Dual-Zone Climate Control" },
      new Feature { Id = 32, NameOfFeatures = "Power Folding Mirrors" },
      new Feature { Id = 33, NameOfFeatures = "Lane Keeping Assist" },
      new Feature { Id = 34, NameOfFeatures = "Electric Power Steering" },
      new Feature { Id = 35, NameOfFeatures = "Turbocharged Engine" },
      new Feature { Id = 36, NameOfFeatures = "Carbon Fiber Trim" },
      new Feature { Id = 37, NameOfFeatures = "Active Noise Cancellation" },
      new Feature { Id = 38, NameOfFeatures = "All-Wheel Drive" },
      new Feature { Id = 39, NameOfFeatures = "Front Parking Sensors" },
      new Feature { Id = 40, NameOfFeatures = "Sport Mode" },
      new Feature { Id = 41, NameOfFeatures = "Wireless Smartphone Charging" },
      new Feature { Id = 42, NameOfFeatures = "Massaging Seats" },
      new Feature { Id = 43, NameOfFeatures = "Self-Healing Paint" },
      new Feature { Id = 44, NameOfFeatures = "Night Vision" },
      new Feature { Id = 45, NameOfFeatures = "Active Rear Spoiler" },
      new Feature { Id = 46, NameOfFeatures = "Heads-Up Display with Navigation" },
      new Feature { Id = 47, NameOfFeatures = "Wireless Internet Access" },
      new Feature { Id = 48, NameOfFeatures = "Active Suspension" },
      new Feature { Id = 49, NameOfFeatures = "Power Adjustable Steering Wheel" },
      new Feature { Id = 50, NameOfFeatures = "Touchscreen Control Panel" }
  );

            modelBuilder.Entity<Image>().HasData(
                new Image { Id = 1, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624215/toyota-corolla1_b4potk.jpg", CarId = 1, Order = 1 },
                new Image { Id = 2, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624216/toyota-corolla2_n7shyh.jpg", CarId = 1, Order = 2 },
                new Image { Id = 3, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624216/toyota-corolla3_dho7dm.jpg", CarId = 1, Order = 3 },
                new Image { Id = 4, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624217/toyota-corolla4_cfo28b.jpg", CarId = 1, Order = 4 },
                new Image { Id = 5, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624172/honda-civic1_rnvnry.png", CarId = 2, Order = 1 },
                new Image { Id = 6, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624173/honda-civic2_gvys4w.png", CarId = 2, Order = 2 },
                new Image { Id = 7, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624174/honda-civic3_jltzua.png", CarId = 2, Order = 3 },
                new Image { Id = 8, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624175/honda-civic4_frqcl3.png", CarId = 2, Order = 4 },
                new Image { Id = 9, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624119/bmw-420i1_nxmy5j.png", CarId = 4, Order = 1 },
                new Image { Id = 10, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624124/bmw-420i7_y9o1y9.png", CarId = 4, Order = 2 },
                new Image { Id = 11, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624120/bmw-420i2_iokhet.png", CarId = 4, Order = 3 },
                new Image { Id = 12, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624121/bmw-420i3_ldnjlf.png", CarId = 4, Order = 4 },
                new Image { Id = 13, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624122/bmw-420i4_ridevu.png", CarId = 4, Order = 5 },
                new Image { Id = 14, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624122/bmw-420i5_q10b3d.png", CarId = 4, Order = 6 },
                new Image { Id = 15, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624123/bmw-420i6_wtzvrn.png", CarId = 4, Order = 7 },
                new Image { Id = 16, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624129/c300-1_xa9fzu.webp", CarId = 5, Order = 1 },
                new Image { Id = 17, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624129/c300-2_szhfxp.webp", CarId = 5, Order = 2 },
                new Image { Id = 18, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624130/c300-3_rdbinb.webp", CarId = 5, Order = 3 },
                new Image { Id = 19, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624131/c300-4_bgrzgs.webp", CarId = 5, Order = 4 },
                new Image { Id = 20, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624132/c300-5_dve7qn.webp", CarId = 5, Order = 5 },
                new Image { Id = 21, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624132/c300-6_h9enpn.webp", CarId = 5, Order = 6 },
                new Image { Id = 22, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624147/ford-mustang-1_bvjyjo.webp", CarId = 3, Order = 1 },
                new Image { Id = 23, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624148/ford-mustang-2_tbc9od.webp", CarId = 3, Order = 2 },
                new Image { Id = 24, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624149/ford-mustang-3_wsj9bd.webp", CarId = 3, Order = 3 },
                new Image { Id = 25, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624149/ford-mustang-4_abjtqh.webp", CarId = 3, Order = 4 },
                new Image { Id = 26, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624150/ford-mustang-5_d2g57e.webp", CarId = 3, Order = 5 },
                new Image { Id = 27, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624151/ford-mustang-6_oi7yjf.webp", CarId = 3, Order = 6 },
                new Image { Id = 28, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624171/ford-mustang-7_gfhjq4.webp", CarId = 3, Order = 7 },
                new Image { Id = 29, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624171/ford-mustang-8_l8owjg.webp", CarId = 3, Order = 8 },
                new Image { Id = 30, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624101/audi-r8-1_izlqmr.jpg", CarId = 6, Order = 1 },
                new Image { Id = 31, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624102/audi-r8-2_bwgt3m.jpg", CarId = 6, Order = 2 },
                new Image { Id = 32, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624105/audi-r8-7_qcjsl4.jpg", CarId = 6, Order = 3 },
                new Image { Id = 33, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624104/audi-r8-5_c6hugv.jpg", CarId = 6, Order = 4 },
                new Image { Id = 34, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624105/audi-r8-6_wtw31c.jpg", CarId = 6, Order = 5 },
                new Image { Id = 35, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624103/audi-r8-4_wtfr0f.jpg", CarId = 6, Order = 6 },
                new Image { Id = 36, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624102/audi-r8-3_hrsi4g.jpg", CarId = 6, Order = 7 },
                new Image { Id = 37, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624106/audi-r8-8_uixxgi.jpg", CarId = 6, Order = 8 },
                new Image { Id = 38, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624175/lambo-hur-1_il42yl.jpg", CarId = 7, Order = 1 },
                new Image { Id = 39, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624176/lambo-hur-2_odjisi.jpg", CarId = 7, Order = 2 },
                new Image { Id = 40, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624177/lambo-hur-3_yyl1xk.jpg", CarId = 7, Order = 3 },
                new Image { Id = 41, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624178/lambo-hur-4_errnh3.jpg", CarId = 7, Order = 4 },
                new Image { Id = 42, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624178/lambo-hur-5_lako1f.jpg", CarId = 7, Order = 5 },
                new Image { Id = 43, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624198/porsche-gt3-1_aw1eyn.webp", CarId = 8, Order = 1 },
                new Image { Id = 44, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624199/porsche-gt3-2_viiwrz.webp", CarId = 8, Order = 2 },
                new Image { Id = 45, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624200/porsche-gt3-4_ozoddo.webp", CarId = 8, Order = 3 },
                new Image { Id = 46, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624201/porsche-gt3-5_r8rh4a.webp", CarId = 8, Order = 4 },
                new Image { Id = 47, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624200/porsche-gt3-3_ryxvfh.webp", CarId = 8, Order = 5 },
                new Image { Id = 48, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624202/porsche-gt3-6_axhlgo.webp", CarId = 8, Order = 6 },
                new Image { Id = 49, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624203/porsche-gt3-7_qrihj8.webp", CarId = 8, Order = 7 },
                new Image { Id = 50, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624203/porsche-gt3-8_jxqgaa.webp", CarId = 8, Order = 8},
                new Image { Id = 51, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624210/tesla-s-1_lpjunc.webp", CarId = 9, Order = 1 },
                new Image { Id = 52, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624211/tesla-s-2_f3xqwp.webp", CarId = 9, Order = 2 },
                new Image { Id = 53, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624212/tesla-s-3_thbj4a.webp", CarId = 9, Order = 3 },
                new Image { Id = 54, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624213/tesla-s-4_gpgpcz.webp", CarId = 9, Order = 4 },
                new Image { Id = 55, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624213/tesla-s-5_zwunpd.webp", CarId = 9, Order = 5 },
                new Image { Id = 56, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624214/tesla-s-6_q9yrxu.webp", CarId = 9, Order = 6 },
                new Image { Id = 57, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624141/ferrari-f-1_adyn0z.webp", CarId = 10, Order = 1 },
                new Image { Id = 58, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624142/ferrari-f-2_ccxpeg.webp", CarId = 10, Order = 2 },
                new Image { Id = 59, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624143/ferrari-f-3_orloyj.webp", CarId = 10, Order = 3 },
                new Image { Id = 60, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624144/ferrari-f-4_bdztgj.webp", CarId = 10, Order = 4 },
                new Image { Id = 61, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624144/ferrari-f-5_s7ru1h.webp", CarId = 10, Order = 5 },
                new Image { Id = 62, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624145/ferrari-f-6_taupu5.webp", CarId = 10, Order = 6 },
                new Image { Id = 63, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624146/ferrari-f-7_kzoecy.webp", CarId = 10, Order = 7 },
                new Image { Id = 64, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624146/ferrari-f-8_dn9g53.webp", CarId = 10, Order = 8 },
                new Image { Id = 65, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624190/phanthom-1_uh4lhj.webp", CarId = 11, Order = 1 },
                new Image { Id = 66, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624191/phanthom-2_ruvpjz.webp", CarId = 11, Order = 2 },
                new Image { Id = 67, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624192/phanthom-3_clwtzg.webp", CarId = 11, Order = 3 },
                new Image { Id = 68, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624192/phanthom-4_fso0mv.webp", CarId = 11, Order = 4 },
                new Image { Id = 69, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624193/phanthom-5_htnvgs.webp", CarId = 11, Order = 5 },
                new Image { Id = 70, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624194/phanthom-6_e6u4tc.webp", CarId = 11, Order = 6 },
                new Image { Id = 71, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624195/phanthom-7_pnuqus.webp", CarId = 11, Order = 7 },
                new Image { Id = 72, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624195/phanthom-8_g2jcvh.webp", CarId = 11, Order = 8 },
                new Image { Id = 73, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624196/phanthom-9_eydedv.webp", CarId = 11, Order = 9 },
                new Image { Id = 74, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624197/phanthom-10_tac7j7.webp", CarId = 11, Order = 10 },
                new Image { Id = 75, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624197/phanthom-11_mmhpah.webp", CarId = 11, Order = 11 },
                new Image { Id = 76, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624110/bentley-continental-gt-1_jtijlv.webp", CarId = 12, Order = 1 },
                new Image { Id = 77, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624111/bentley-continental-gt-2_gkaxkc.webp", CarId = 12, Order = 2 },
                new Image { Id = 78, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624111/bentley-continental-gt-3_hgzvhk.webp", CarId = 12, Order = 3 },
                new Image { Id = 79, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624112/bentley-continental-gt-4_gksbaw.webp", CarId = 12, Order = 4 },
                new Image { Id = 80, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624113/bentley-continental-gt-5_ansuex.webp", CarId = 12, Order = 5 },
                new Image { Id = 81, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624114/bentley-continental-gt-6_dmhczo.webp", CarId = 12, Order = 6 },
                new Image { Id = 82, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624115/bentley-continental-gt-7_wa6hzb.webp", CarId = 12, Order = 7 },
                new Image { Id = 83, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624115/bentley-continental-gt-8_zfce2y.webp", CarId = 12, Order = 8 },
                new Image { Id = 84, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624116/bentley-continental-gt-9_ailjxc.webp", CarId = 12, Order = 9 },
                new Image { Id = 85, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624117/bentley-continental-gt-10_zuafdn.webp", CarId = 12, Order = 10 },
                new Image { Id = 86, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624118/bentley-continental-gt-11_dpgk0n.webp", CarId = 12, Order = 11},
                new Image { Id = 87, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624119/bentley-continental-gt-12_qix8df.webp", CarId = 12, Order = 12 },
                new Image { Id = 88, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624184/mc-720s-1_gfpc3h.webp", CarId = 13, Order = 1 },
                new Image { Id = 89, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624185/mc-720s-2_chjno0.webp", CarId = 13, Order = 2 },
                new Image { Id = 90, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624186/mc-720s-3_yyid0a.webp", CarId = 13, Order = 3 },
                new Image { Id = 91, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624187/mc-720s-4_byfzl3.webp", CarId = 13, Order = 4 },
                new Image { Id = 92, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624187/mc-720s-5_xfm1ak.webp", CarId = 13, Order = 5 },
                new Image { Id = 93, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624188/mc-720s-6_jchqap.webp", CarId = 13, Order = 6 },
                new Image { Id = 94, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624189/mc-720s-7_qhapko.webp", CarId = 13, Order = 7 },
                new Image { Id = 95, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624088/aston-dbx-1_fxbd0z.webp", CarId = 14, Order = 1 },
                new Image { Id = 96, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624089/aston-dbx-2_pokk3x.webp", CarId = 14, Order = 2 },
                new Image { Id = 97, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624090/aston-dbx-3_hr8new.webp", CarId = 14, Order = 3 },
                new Image { Id = 98, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624091/aston-dbx-4_mdqqwi.webp", CarId = 14, Order = 4 },
                new Image { Id = 99, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624091/aston-dbx-5_sjbfzg.webp", CarId = 14, Order = 5 },
                new Image { Id = 100, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624092/aston-dbx-6_n26der.webp", CarId = 14, Order = 6 },
                new Image { Id = 101, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624093/aston-dbx-7_rde45u.webp", CarId = 14, Order = 7 },
                new Image { Id = 102, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624093/aston-dbx-8_g56hgy.webp", CarId = 14, Order = 8 },
                new Image { Id = 103, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624179/lexus-lx-1_oy7dob.webp", CarId = 15, Order = 1 },
                new Image { Id = 104, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624180/lexus-lx-2_gbutlv.webp", CarId = 15, Order = 2 },
                new Image { Id = 105, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624181/lexus-lx-3_qauteg.webp", CarId = 15, Order = 3 },
                new Image { Id = 106, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624181/lexus-lx-4_o36dcg.webp", CarId = 15, Order = 4 },
                new Image { Id = 107, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624182/lexus-lx-5_sltxmf.webp", CarId = 15, Order = 5 },
                new Image { Id = 108, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624183/lexus-lx-6_tfpdn9.webp", CarId = 15, Order = 6 },
                new Image { Id = 109, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624184/lexus-lx-7_sh3rbv.webp", CarId = 15, Order = 7 },
                new Image { Id = 110, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624084/amg-gt-1_sarh5f.webp", CarId = 16, Order = 1 },
                new Image { Id = 111, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624084/amg-gt-2_zkxqad.webp", CarId = 16, Order = 2 },
                new Image { Id = 112, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624085/amg-gt-3_bsf98p.webp", CarId = 16, Order = 3 },
                new Image { Id = 113, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624085/amg-gt-4_zjcdzb.webp", CarId = 16, Order = 4 },
                new Image { Id = 114, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624086/amg-gt-5_qmk6z5.webp", CarId = 16, Order = 5 },
                new Image { Id = 115, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624086/amg-gt-6_qeovuo.webp", CarId = 16, Order = 6 },
                new Image { Id = 116, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624087/amg-gt-7_dzuweo.webp", CarId = 16, Order = 7 },
                new Image { Id = 117, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624088/amg-gt-8_s7wcnc.webp", CarId = 16, Order = 8 },
                new Image { Id = 118, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624094/audi-q8-1_iehvtl.webp", CarId = 17, Order = 1 },
                new Image { Id = 119, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624095/audi-q8-2_k1zvqr.webp", CarId = 17, Order = 2 },
                new Image { Id = 120, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624096/audi-q8-3_se4pci.webp", CarId = 17, Order = 3 },
                new Image { Id = 121, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624096/audi-q8-4_lp8szg.webp", CarId = 17, Order = 4 },
                new Image { Id = 122, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624097/audi-q8-5_rmh0xi.webp", CarId = 17, Order = 5 },
                new Image { Id = 123, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624098/audi-q8-6_lhuxkd.webp", CarId = 17, Order = 6 },
                new Image { Id = 124, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624098/audi-q8-7_mfgkde.webp", CarId = 17, Order = 7 },
                new Image { Id = 125, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624099/audi-q8-8_uvjc4w.webp", CarId = 17, Order = 8 },
                new Image { Id = 126, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624100/audi-q8-9_q48agf.webp", CarId = 17, Order = 9 },
                new Image { Id = 127, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624124/bmw-m4-1_wrcccj.webp", CarId = 18, Order = 1 },
                new Image { Id = 128, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624125/bmw-m4-2_zvh1qm.webp", CarId = 18, Order = 2 },
                new Image { Id = 129, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624126/bmw-m4-3_tcnfuc.webp", CarId = 18, Order = 3 },
                new Image { Id = 130, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624127/bmw-m4-4_u7ibmo.webp", CarId = 18, Order = 4 },
                new Image { Id = 131, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624128/bmw-m4-5_u3rnbk.webp", CarId = 18, Order = 5 },
                new Image { Id = 132, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624128/bmw-m4-6_gk7knn.webp", CarId = 18, Order = 6 },
                new Image { Id = 133, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624133/camry-1_wo9lkk.webp", CarId = 19, Order = 1 },
                new Image { Id = 134, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624134/camry-2_etxvu2.webp", CarId = 19, Order = 2 },
                new Image { Id = 135, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624134/camry-3_lb0kqw.webp", CarId = 19, Order = 3 },
                new Image { Id = 136, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624135/camry-4_c1fqal.webp", CarId = 19, Order = 4 },
                new Image { Id = 137, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624136/camry-5_njv1ok.webp", CarId = 19, Order = 5 },
                new Image { Id = 138, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624137/camry-6_sdwbt0.webp", CarId = 19, Order = 6 },
                new Image { Id = 139, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624137/camry-7_jw8pk1.webp", CarId = 19, Order = 7 },
                new Image { Id = 140, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624138/cybertruck-1_s3nz5x.webp", CarId = 20, Order = 1 },
                new Image { Id = 141, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624139/cybertruck-2_jmlgm8.webp", CarId = 20, Order = 2 },
                new Image { Id = 142, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624139/cybertruck-3_num8xy.webp", CarId = 20, Order = 3},
                new Image { Id = 143, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624140/cybertruck-4_moirmd.webp", CarId = 20, Order = 4 },
                new Image { Id = 144, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624141/cybertruck-5_l3ldx9.webp", CarId = 20, Order = 5 },
                new Image { Id = 145, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624204/rover-1_dbhrsn.webp", CarId = 21, Order = 1 },
                new Image { Id = 146, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624205/rover-2_ewg7kg.webp", CarId = 21, Order = 2 },
                new Image { Id = 147, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624205/rover-3_ocenlp.webp", CarId = 21, Order = 3 },
                new Image { Id = 148, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624206/rover-4_cqy61j.webp", CarId = 21, Order = 4 },
                new Image { Id = 149, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624207/rover-5_jpjdek.webp", CarId = 21, Order = 5 },
                new Image { Id = 150, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624207/rover-6_ffmgs5.webp", CarId = 21, Order = 6 },
                new Image { Id = 151, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624208/rover-7_y5nvgx.webp", CarId = 21, Order = 7 },
                new Image { Id = 152, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624209/rover-8_coy3zd.webp", CarId = 21, Order = 8 },
                new Image { Id = 153, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624210/rover-9_ygo8xm.webp", CarId = 21, Order = 9 },
                new Image { Id = 154, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624218/toyota-supra-1_rlschs.webp", CarId = 22, Order = 1 },
                new Image { Id = 155, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624218/toyota-supra-2_mgzqxi.webp", CarId = 22, Order = 2 },
                new Image { Id = 156, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624219/toyota-supra-3_p5v7h4.webp", CarId = 22, Order = 3 },
                new Image { Id = 157, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624220/toyota-supra-4_lqxnfq.webp", CarId = 22, Order = 4 },
                new Image { Id = 158, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624221/toyota-supra-5_bdk5pw.webp", CarId = 22, Order = 5 },
                new Image { Id = 159, Url = "https://res.cloudinary.com/dhibmotzx/image/upload/v1739624221/toyota-supra-6_dmnvea.webp", CarId = 22, Order = 6 }
                );
            modelBuilder.Entity<CarFeature>().HasData(
            new CarFeature { Id = 1, CarId = 1, FeatureId = 1 },
            new CarFeature { Id = 2, CarId = 1, FeatureId = 3 },
            new CarFeature { Id = 3, CarId = 1, FeatureId = 5 },
            new CarFeature { Id = 4, CarId = 1, FeatureId = 6 },
            new CarFeature { Id = 5, CarId = 1, FeatureId = 7 },
            new CarFeature { Id = 6, CarId = 1, FeatureId = 23 },

            new CarFeature { Id = 7, CarId = 2, FeatureId = 1 },
            new CarFeature { Id = 8, CarId = 2, FeatureId = 3 },
            new CarFeature { Id = 9, CarId = 2, FeatureId = 5 },
            new CarFeature { Id = 10, CarId = 2, FeatureId = 6 },
            new CarFeature { Id = 11, CarId = 2, FeatureId = 7 },
            new CarFeature { Id = 12, CarId = 2, FeatureId = 9 },
            new CarFeature { Id = 13, CarId = 2, FeatureId = 17 },
            new CarFeature { Id = 14, CarId = 2, FeatureId = 19 },
            new CarFeature { Id = 15, CarId = 2, FeatureId = 20 },
            new CarFeature { Id = 16, CarId = 2, FeatureId = 21 },
            new CarFeature { Id = 17, CarId = 2, FeatureId = 23 },
            new CarFeature { Id = 18, CarId = 2, FeatureId = 28 },
            new CarFeature { Id = 19, CarId = 2, FeatureId = 30 },
            new CarFeature { Id = 20, CarId = 2, FeatureId = 31 },
            new CarFeature { Id = 21, CarId = 2, FeatureId = 33 },
            new CarFeature { Id = 22, CarId = 2, FeatureId = 38 },

            new CarFeature { Id = 23, CarId = 3, FeatureId = 1 },
            new CarFeature { Id = 24, CarId = 3, FeatureId = 3 },
            new CarFeature { Id = 25, CarId = 3, FeatureId = 5 },
            new CarFeature { Id = 26, CarId = 3, FeatureId = 6 },
            new CarFeature { Id = 27, CarId = 3, FeatureId = 7 },
            new CarFeature { Id = 28, CarId = 3, FeatureId = 9 },
            new CarFeature { Id = 29, CarId = 3, FeatureId = 17 },
            new CarFeature { Id = 30, CarId = 3, FeatureId = 19 },
            new CarFeature { Id = 31, CarId = 3, FeatureId = 20 },
            new CarFeature { Id = 32, CarId = 3, FeatureId = 21 },
            new CarFeature { Id = 33, CarId = 3, FeatureId = 28 },
            new CarFeature { Id = 34, CarId = 3, FeatureId = 33 },
            new CarFeature { Id = 35, CarId = 3, FeatureId = 40 },
            new CarFeature { Id = 36, CarId = 3, FeatureId = 42 },
            new CarFeature { Id = 37, CarId = 3, FeatureId = 45 },
            new CarFeature { Id = 38, CarId = 3, FeatureId = 46 },

            new CarFeature { Id = 39, CarId = 4, FeatureId = 1 },
            new CarFeature { Id = 40, CarId = 4, FeatureId = 3 },
            new CarFeature { Id = 41, CarId = 4, FeatureId = 5 },
            new CarFeature { Id = 42, CarId = 4, FeatureId = 6 },
            new CarFeature { Id = 43, CarId = 4, FeatureId = 7 },
            new CarFeature { Id = 44, CarId = 4, FeatureId = 9 },
            new CarFeature { Id = 45, CarId = 4, FeatureId = 17 },
            new CarFeature { Id = 46, CarId = 4, FeatureId = 19 },
            new CarFeature { Id = 47, CarId = 4, FeatureId = 20 },
            new CarFeature { Id = 48, CarId = 4, FeatureId = 21 },
            new CarFeature { Id = 49, CarId = 4, FeatureId = 23 },
            new CarFeature { Id = 50, CarId = 4, FeatureId = 28 },
            new CarFeature { Id = 51, CarId = 4, FeatureId = 30 },
            new CarFeature { Id = 52, CarId = 4, FeatureId = 31 },
            new CarFeature { Id = 53, CarId = 4, FeatureId = 33 },
            new CarFeature { Id = 54, CarId = 4, FeatureId = 34 },
            new CarFeature { Id = 55, CarId = 4, FeatureId = 36 },
            new CarFeature { Id = 56, CarId = 4, FeatureId = 40 },
            new CarFeature { Id = 57, CarId = 4, FeatureId = 41 },
            new CarFeature { Id = 58, CarId = 4, FeatureId = 45 },
            new CarFeature { Id = 59, CarId = 4, FeatureId = 47 },
            new CarFeature { Id = 60, CarId = 4, FeatureId = 33 },
            new CarFeature { Id = 61, CarId = 4, FeatureId = 34 },

            new CarFeature { Id = 62, CarId = 5, FeatureId = 1 },
            new CarFeature { Id = 63, CarId = 5, FeatureId = 3 },
            new CarFeature { Id = 64, CarId = 5, FeatureId = 5 },
            new CarFeature { Id = 65, CarId = 5, FeatureId = 6 },
            new CarFeature { Id = 66, CarId = 5, FeatureId = 7 },
            new CarFeature { Id = 67, CarId = 5, FeatureId = 9 },
            new CarFeature { Id = 68, CarId = 5, FeatureId = 17 },
            new CarFeature { Id = 69, CarId = 5, FeatureId = 19 },
            new CarFeature { Id = 70, CarId = 5, FeatureId = 20 },
            new CarFeature { Id = 71, CarId = 5, FeatureId = 21 },
            new CarFeature { Id = 72, CarId = 5, FeatureId = 23 },
            new CarFeature { Id = 73, CarId = 5, FeatureId = 28 },
            new CarFeature { Id = 74, CarId = 5, FeatureId = 30 },
            new CarFeature { Id = 75, CarId = 5, FeatureId = 31 },
            new CarFeature { Id = 76, CarId = 5, FeatureId = 33 },
            new CarFeature { Id = 77, CarId = 5, FeatureId = 34 },
            new CarFeature { Id = 78, CarId = 5, FeatureId = 40 },
            new CarFeature { Id = 79, CarId = 5, FeatureId = 41 },
            new CarFeature { Id = 80, CarId = 5, FeatureId = 45 },
            new CarFeature { Id = 81, CarId = 5, FeatureId = 47 },


            new CarFeature { Id = 82, CarId = 6, FeatureId = 1 },
            new CarFeature { Id = 83, CarId = 6, FeatureId = 3 },
            new CarFeature { Id = 84, CarId = 6, FeatureId = 5 },
            new CarFeature { Id = 85, CarId = 6, FeatureId = 6 },
            new CarFeature { Id = 86, CarId = 6, FeatureId = 7 },
            new CarFeature { Id = 87, CarId = 6, FeatureId = 9 },
            new CarFeature { Id = 88, CarId = 6, FeatureId = 17 },
            new CarFeature { Id = 89, CarId = 6, FeatureId = 19 },
            new CarFeature { Id = 90, CarId = 6, FeatureId = 20 },
            new CarFeature { Id = 91, CarId = 6, FeatureId = 21 },
            new CarFeature { Id = 92, CarId = 6, FeatureId = 23 },
            new CarFeature { Id = 93, CarId = 6, FeatureId = 28 },
            new CarFeature { Id = 94, CarId = 6, FeatureId = 30 },
            new CarFeature { Id = 95, CarId = 6, FeatureId = 31 },
            new CarFeature { Id = 96, CarId = 6, FeatureId = 33 },
            new CarFeature { Id = 97, CarId = 6, FeatureId = 34 },
            new CarFeature { Id = 98, CarId = 6, FeatureId = 40 },
            new CarFeature { Id = 99, CarId = 6, FeatureId = 41 },
            new CarFeature { Id = 100, CarId = 6, FeatureId = 45 },
            new CarFeature { Id = 101, CarId = 6, FeatureId = 47 },

            new CarFeature { Id = 102, CarId = 7, FeatureId = 1 },
            new CarFeature { Id = 103, CarId = 7, FeatureId = 3 },
            new CarFeature { Id = 104, CarId = 7, FeatureId = 5 },
            new CarFeature { Id = 105, CarId = 7, FeatureId = 6 },
            new CarFeature { Id = 106, CarId = 7, FeatureId = 7 },
            new CarFeature { Id = 107, CarId = 7, FeatureId = 9 },
            new CarFeature { Id = 108, CarId = 7, FeatureId = 17 },
            new CarFeature { Id = 109, CarId = 7, FeatureId = 19 },
            new CarFeature { Id = 110, CarId = 7, FeatureId = 20 },
            new CarFeature { Id = 111, CarId = 7, FeatureId = 23 },
            new CarFeature { Id = 112, CarId = 7, FeatureId = 28 },
            new CarFeature { Id = 113, CarId = 7, FeatureId = 30 },
            new CarFeature { Id = 114, CarId = 7, FeatureId = 31 },
            new CarFeature { Id = 115, CarId = 7, FeatureId = 33 },
            new CarFeature { Id = 116, CarId = 7, FeatureId = 40 },
            new CarFeature { Id = 117, CarId = 7, FeatureId = 41 },
            new CarFeature { Id = 118, CarId = 7, FeatureId = 45 },
            new CarFeature { Id = 119, CarId = 7, FeatureId = 47 },

            new CarFeature { Id = 120, CarId = 8, FeatureId = 1 },
            new CarFeature { Id = 121, CarId = 8, FeatureId = 3 },
            new CarFeature { Id = 122, CarId = 8, FeatureId = 5 },
            new CarFeature { Id = 123, CarId = 8, FeatureId = 6 },
            new CarFeature { Id = 124, CarId = 8, FeatureId = 7 },
            new CarFeature { Id = 125, CarId = 8, FeatureId = 17 },
            new CarFeature { Id = 126, CarId = 8, FeatureId = 20 },
            new CarFeature { Id = 127, CarId = 8, FeatureId = 21 },
            new CarFeature { Id = 128, CarId = 8, FeatureId = 23 },
            new CarFeature { Id = 129, CarId = 8, FeatureId = 28 },
            new CarFeature { Id = 130, CarId = 8, FeatureId = 40 },
            new CarFeature { Id = 131, CarId = 8, FeatureId = 41 },
            new CarFeature { Id = 132, CarId = 8, FeatureId = 45 },
            new CarFeature { Id = 133, CarId = 8, FeatureId = 36 },
            new CarFeature { Id = 134, CarId = 8, FeatureId = 48 },

            new CarFeature { Id = 135, CarId = 9, FeatureId = 1 },
            new CarFeature { Id = 136, CarId = 9, FeatureId = 3 },
            new CarFeature { Id = 137, CarId = 9, FeatureId = 5 },
            new CarFeature { Id = 138, CarId = 9, FeatureId = 6 },
            new CarFeature { Id = 139, CarId = 9, FeatureId = 7 },
            new CarFeature { Id = 140, CarId = 9, FeatureId = 9 },
            new CarFeature { Id = 141, CarId = 9, FeatureId = 17 },
            new CarFeature { Id = 142, CarId = 9, FeatureId = 19 },
            new CarFeature { Id = 143, CarId = 9, FeatureId = 20 },
            new CarFeature { Id = 144, CarId = 9, FeatureId = 21 },
            new CarFeature { Id = 145, CarId = 9, FeatureId = 23 },
            new CarFeature { Id = 146, CarId = 9, FeatureId = 28 },
            new CarFeature { Id = 147, CarId = 9, FeatureId = 30 },
            new CarFeature { Id = 148, CarId = 9, FeatureId = 31 },
            new CarFeature { Id = 149, CarId = 9, FeatureId = 34 },
            new CarFeature { Id = 150, CarId = 9, FeatureId = 40 },
            new CarFeature { Id = 151, CarId = 9, FeatureId = 41 },
            new CarFeature { Id = 152, CarId = 9, FeatureId = 47 },
            new CarFeature { Id = 153, CarId = 9, FeatureId = 48 },

            new CarFeature { Id = 154, CarId = 10, FeatureId = 1 },
            new CarFeature { Id = 155, CarId = 10, FeatureId = 3 },
            new CarFeature { Id = 156, CarId = 10, FeatureId = 5 },
            new CarFeature { Id = 157, CarId = 10, FeatureId = 6 },
            new CarFeature { Id = 158, CarId = 10, FeatureId = 7 },
            new CarFeature { Id = 159, CarId = 10, FeatureId = 9 },
            new CarFeature { Id = 160, CarId = 10, FeatureId = 17 },
            new CarFeature { Id = 161, CarId = 10, FeatureId = 19 },
            new CarFeature { Id = 162, CarId = 10, FeatureId = 20 },
            new CarFeature { Id = 163, CarId = 10, FeatureId = 23 },
            new CarFeature { Id = 164, CarId = 10, FeatureId = 28 },
            new CarFeature { Id = 165, CarId = 10, FeatureId = 30 },
            new CarFeature { Id = 166, CarId = 10, FeatureId = 40 },
            new CarFeature { Id = 167, CarId = 10, FeatureId = 41 },
            new CarFeature { Id = 168, CarId = 10, FeatureId = 45 },
            new CarFeature { Id = 169, CarId = 10, FeatureId = 36 },
            new CarFeature { Id = 170, CarId = 10, FeatureId = 48 },

            new CarFeature { Id = 171, CarId = 11, FeatureId = 1 },
            new CarFeature { Id = 172, CarId = 11, FeatureId = 3 },
            new CarFeature { Id = 173, CarId = 11, FeatureId = 5 },
            new CarFeature { Id = 174, CarId = 11, FeatureId = 6 },
            new CarFeature { Id = 175, CarId = 11, FeatureId = 7 },
            new CarFeature { Id = 176, CarId = 11, FeatureId = 9 },
            new CarFeature { Id = 177, CarId = 11, FeatureId = 17 },
            new CarFeature { Id = 178, CarId = 11, FeatureId = 19 },
            new CarFeature { Id = 179, CarId = 11, FeatureId = 20 },
            new CarFeature { Id = 180, CarId = 11, FeatureId = 21 },
            new CarFeature { Id = 181, CarId = 11, FeatureId = 23 },
            new CarFeature { Id = 182, CarId = 11, FeatureId = 28 },
            new CarFeature { Id = 183, CarId = 11, FeatureId = 30 },
            new CarFeature { Id = 184, CarId = 11, FeatureId = 31 },
            new CarFeature { Id = 185, CarId = 11, FeatureId = 34 },
            new CarFeature { Id = 186, CarId = 11, FeatureId = 40 },
            new CarFeature { Id = 187, CarId = 11, FeatureId = 41 },
            new CarFeature { Id = 188, CarId = 11, FeatureId = 45 },
            new CarFeature { Id = 189, CarId = 11, FeatureId = 47 },
            new CarFeature { Id = 190, CarId = 11, FeatureId = 48 },

            new CarFeature { Id = 191, CarId = 12, FeatureId = 1 },
            new CarFeature { Id = 192, CarId = 12, FeatureId = 3 },
            new CarFeature { Id = 193, CarId = 12, FeatureId = 5 },
            new CarFeature { Id = 194, CarId = 12, FeatureId = 6 },
            new CarFeature { Id = 195, CarId = 12, FeatureId = 7 },
            new CarFeature { Id = 196, CarId = 12, FeatureId = 9 },
            new CarFeature { Id = 197, CarId = 12, FeatureId = 17 },
            new CarFeature { Id = 198, CarId = 12, FeatureId = 19 },
            new CarFeature { Id = 199, CarId = 12, FeatureId = 20 },
            new CarFeature { Id = 200, CarId = 12, FeatureId = 21 },
            new CarFeature { Id = 201, CarId = 12, FeatureId = 23 },
            new CarFeature { Id = 202, CarId = 12, FeatureId = 28 },
            new CarFeature { Id = 203, CarId = 12, FeatureId = 30 },
            new CarFeature { Id = 204, CarId = 12, FeatureId = 31 },
            new CarFeature { Id = 205, CarId = 12, FeatureId = 34 },
            new CarFeature { Id = 206, CarId = 12, FeatureId = 40 },
            new CarFeature { Id = 207, CarId = 12, FeatureId = 41 },
            new CarFeature { Id = 208, CarId = 12, FeatureId = 45 },
            new CarFeature { Id = 209, CarId = 12, FeatureId = 47 },
            new CarFeature { Id = 210, CarId = 12, FeatureId = 48 },

            new CarFeature { Id = 211, CarId = 13, FeatureId = 1 },
            new CarFeature { Id = 212, CarId = 13, FeatureId = 3 },
            new CarFeature { Id = 213, CarId = 13, FeatureId = 5 },
            new CarFeature { Id = 214, CarId = 13, FeatureId = 6 },
            new CarFeature { Id = 215, CarId = 13, FeatureId = 7 },
            new CarFeature { Id = 216, CarId = 13, FeatureId = 9 },
            new CarFeature { Id = 217, CarId = 13, FeatureId = 17 },
            new CarFeature { Id = 218, CarId = 13, FeatureId = 19 },
            new CarFeature { Id = 219, CarId = 13, FeatureId = 20 },
            new CarFeature { Id = 220, CarId = 13, FeatureId = 21 },
            new CarFeature { Id = 221, CarId = 13, FeatureId = 23 },
            new CarFeature { Id = 222, CarId = 13, FeatureId = 28 },
            new CarFeature { Id = 223, CarId = 13, FeatureId = 30 },
            new CarFeature { Id = 224, CarId = 13, FeatureId = 31 },
            new CarFeature { Id = 225, CarId = 13, FeatureId = 34 },
            new CarFeature { Id = 226, CarId = 13, FeatureId = 40 },
            new CarFeature { Id = 227, CarId = 13, FeatureId = 41 },
            new CarFeature { Id = 228, CarId = 13, FeatureId = 45 },
            new CarFeature { Id = 229, CarId = 13, FeatureId = 47 },
            new CarFeature { Id = 230, CarId = 13, FeatureId = 48 },

            new CarFeature { Id = 231, CarId = 14, FeatureId = 1 },
            new CarFeature { Id = 232, CarId = 14, FeatureId = 3 },
            new CarFeature { Id = 233, CarId = 14, FeatureId = 5 },
            new CarFeature { Id = 234, CarId = 14, FeatureId = 6 },
            new CarFeature { Id = 235, CarId = 14, FeatureId = 7 },
            new CarFeature { Id = 236, CarId = 14, FeatureId = 9 },
            new CarFeature { Id = 237, CarId = 14, FeatureId = 17 },
            new CarFeature { Id = 238, CarId = 14, FeatureId = 19 },
            new CarFeature { Id = 239, CarId = 14, FeatureId = 20 },
            new CarFeature { Id = 240, CarId = 14, FeatureId = 21 },
            new CarFeature { Id = 241, CarId = 14, FeatureId = 23 },
            new CarFeature { Id = 242, CarId = 14, FeatureId = 28 },
            new CarFeature { Id = 243, CarId = 14, FeatureId = 30 },
            new CarFeature { Id = 244, CarId = 14, FeatureId = 31 },
            new CarFeature { Id = 245, CarId = 14, FeatureId = 34 },
            new CarFeature { Id = 246, CarId = 14, FeatureId = 40 },
            new CarFeature { Id = 247, CarId = 14, FeatureId = 41 },
            new CarFeature { Id = 248, CarId = 14, FeatureId = 45 },
            new CarFeature { Id = 249, CarId = 14, FeatureId = 47 },
            new CarFeature { Id = 250, CarId = 14, FeatureId = 48 },
            new CarFeature { Id = 251, CarId = 14, FeatureId = 36 },
            new CarFeature { Id = 252, CarId = 14, FeatureId = 46 },
            new CarFeature { Id = 253, CarId = 14, FeatureId = 42 },
            new CarFeature { Id = 254, CarId = 14, FeatureId = 43 },
            new CarFeature { Id = 255, CarId = 14, FeatureId = 44 },
            new CarFeature { Id = 256, CarId = 14, FeatureId = 49 },
            new CarFeature { Id = 257, CarId = 14, FeatureId = 50 },

            new CarFeature { Id = 258, CarId = 15, FeatureId = 1 },
            new CarFeature { Id = 259, CarId = 15, FeatureId = 5 },
            new CarFeature { Id = 260, CarId = 15, FeatureId = 6 },
            new CarFeature { Id = 261, CarId = 15, FeatureId = 7 },
            new CarFeature { Id = 262, CarId = 15, FeatureId = 9 },
            new CarFeature { Id = 263, CarId = 15, FeatureId = 17 },
            new CarFeature { Id = 264, CarId = 15, FeatureId = 19 },
            new CarFeature { Id = 265, CarId = 15, FeatureId = 23 },
            new CarFeature { Id = 266, CarId = 15, FeatureId = 30 },
            new CarFeature { Id = 267, CarId = 15, FeatureId = 40 },

            new CarFeature { Id = 268, CarId = 16, FeatureId = 1 },
            new CarFeature { Id = 269, CarId = 16, FeatureId = 3 },
            new CarFeature { Id = 270, CarId = 16, FeatureId = 5 },
            new CarFeature { Id = 271, CarId = 16, FeatureId = 6 },
            new CarFeature { Id = 272, CarId = 16, FeatureId = 7 },
            new CarFeature { Id = 273, CarId = 16, FeatureId = 9 },
            new CarFeature { Id = 274, CarId = 16, FeatureId = 17 },
            new CarFeature { Id = 275, CarId = 16, FeatureId = 19 },
            new CarFeature { Id = 276, CarId = 16, FeatureId = 20 },
            new CarFeature { Id = 277, CarId = 16, FeatureId = 21 },
            new CarFeature { Id = 278, CarId = 16, FeatureId = 23 },
            new CarFeature { Id = 279, CarId = 16, FeatureId = 28 },
            new CarFeature { Id = 280, CarId = 16, FeatureId = 30 },
            new CarFeature { Id = 281, CarId = 16, FeatureId = 31 },
            new CarFeature { Id = 282, CarId = 16, FeatureId = 34 },
            new CarFeature { Id = 283, CarId = 16, FeatureId = 40 },
            new CarFeature { Id = 284, CarId = 16, FeatureId = 41 },
            new CarFeature { Id = 285, CarId = 16, FeatureId = 45 },
            new CarFeature { Id = 286, CarId = 16, FeatureId = 47 },
            new CarFeature { Id = 287, CarId = 16, FeatureId = 48 },
            new CarFeature { Id = 288, CarId = 16, FeatureId = 36 },
            new CarFeature { Id = 289, CarId = 16, FeatureId = 46 },
            new CarFeature { Id = 290, CarId = 16, FeatureId = 42 },
            new CarFeature { Id = 291, CarId = 16, FeatureId = 43 },
            new CarFeature { Id = 292, CarId = 16, FeatureId = 44 },
            new CarFeature { Id = 293, CarId = 16, FeatureId = 49 },
            new CarFeature { Id = 294, CarId = 16, FeatureId = 50 },

            new CarFeature { Id = 295, CarId = 17, FeatureId = 1 },
            new CarFeature { Id = 296, CarId = 17, FeatureId = 3 },
            new CarFeature { Id = 297, CarId = 17, FeatureId = 5 },
            new CarFeature { Id = 298, CarId = 17, FeatureId = 6 },
            new CarFeature { Id = 299, CarId = 17, FeatureId = 7 },
            new CarFeature { Id = 300, CarId = 17, FeatureId = 9 },
            new CarFeature { Id = 301, CarId = 17, FeatureId = 17 },
            new CarFeature { Id = 302, CarId = 17, FeatureId = 19 },
            new CarFeature { Id = 303, CarId = 17, FeatureId = 20 },
            new CarFeature { Id = 304, CarId = 17, FeatureId = 21 },
            new CarFeature { Id = 305, CarId = 17, FeatureId = 23 },
            new CarFeature { Id = 306, CarId = 17, FeatureId = 28 },
            new CarFeature { Id = 307, CarId = 17, FeatureId = 30 },
            new CarFeature { Id = 308, CarId = 17, FeatureId = 31 },
            new CarFeature { Id = 309, CarId = 17, FeatureId = 34 },
            new CarFeature { Id = 310, CarId = 17, FeatureId = 40 },
            new CarFeature { Id = 311, CarId = 17, FeatureId = 41 },

            new CarFeature { Id = 312, CarId = 18, FeatureId = 1 },
            new CarFeature { Id = 313, CarId = 18, FeatureId = 3 },
            new CarFeature { Id = 314, CarId = 18, FeatureId = 5 },
            new CarFeature { Id = 315, CarId = 18, FeatureId = 6 },
            new CarFeature { Id = 316, CarId = 18, FeatureId = 7 },
            new CarFeature { Id = 317, CarId = 18, FeatureId = 9 },
            new CarFeature { Id = 318, CarId = 18, FeatureId = 17 },
            new CarFeature { Id = 319, CarId = 18, FeatureId = 19 },
            new CarFeature { Id = 320, CarId = 18, FeatureId = 20 },
            new CarFeature { Id = 321, CarId = 18, FeatureId = 21 },
            new CarFeature { Id = 322, CarId = 18, FeatureId = 23 },
            new CarFeature { Id = 323, CarId = 18, FeatureId = 28 },
            new CarFeature { Id = 324, CarId = 18, FeatureId = 30 },
            new CarFeature { Id = 325, CarId = 18, FeatureId = 31 },
            new CarFeature { Id = 326, CarId = 18, FeatureId = 34 },
            new CarFeature { Id = 327, CarId = 18, FeatureId = 40 },
            new CarFeature { Id = 328, CarId = 18, FeatureId = 41 },
            new CarFeature { Id = 329, CarId = 18, FeatureId = 45 },
            new CarFeature { Id = 330, CarId = 18, FeatureId = 47 },

            new CarFeature { Id = 331, CarId = 19, FeatureId = 1 },
            new CarFeature { Id = 332, CarId = 19, FeatureId = 5 },
            new CarFeature { Id = 333, CarId = 19, FeatureId = 6 },
            new CarFeature { Id = 334, CarId = 19, FeatureId = 7 },
            new CarFeature { Id = 335, CarId = 19, FeatureId = 9 },
            new CarFeature { Id = 336, CarId = 19, FeatureId = 17 },

            new CarFeature { Id = 337, CarId = 20, FeatureId = 1 },
            new CarFeature { Id = 338, CarId = 20, FeatureId = 5 },
            new CarFeature { Id = 339, CarId = 20, FeatureId = 6 },
            new CarFeature { Id = 340, CarId = 20, FeatureId = 7 },
            new CarFeature { Id = 341, CarId = 20, FeatureId = 9 },
            new CarFeature { Id = 342, CarId = 20, FeatureId = 17 },
            new CarFeature { Id = 343, CarId = 20, FeatureId = 19 },
            new CarFeature { Id = 344, CarId = 20, FeatureId = 23 },
            new CarFeature { Id = 345, CarId = 20, FeatureId = 30 },

            new CarFeature { Id = 346, CarId = 21, FeatureId = 1 },
            new CarFeature { Id = 347, CarId = 21, FeatureId = 3 },
            new CarFeature { Id = 348, CarId = 21, FeatureId = 5 },
            new CarFeature { Id = 349, CarId = 21, FeatureId = 6 },
            new CarFeature { Id = 350, CarId = 21, FeatureId = 7 },
            new CarFeature { Id = 351, CarId = 21, FeatureId = 9 },
            new CarFeature { Id = 352, CarId = 21, FeatureId = 17 },
            new CarFeature { Id = 353, CarId = 21, FeatureId = 19 },
            new CarFeature { Id = 354, CarId = 21, FeatureId = 20 },
            new CarFeature { Id = 355, CarId = 21, FeatureId = 21 },
            new CarFeature { Id = 356, CarId = 21, FeatureId = 23 },
            new CarFeature { Id = 357, CarId = 21, FeatureId = 28 },
            new CarFeature { Id = 358, CarId = 21, FeatureId = 30 },
            new CarFeature { Id = 359, CarId = 21, FeatureId = 31 },
            new CarFeature { Id = 360, CarId = 21, FeatureId = 34 },
            new CarFeature { Id = 361, CarId = 21, FeatureId = 40 },
            new CarFeature { Id = 362, CarId = 21, FeatureId = 41 },
            new CarFeature { Id = 363, CarId = 21, FeatureId = 45 },
            new CarFeature { Id = 364, CarId = 21, FeatureId = 47 },
            new CarFeature { Id = 365, CarId = 21, FeatureId = 48 },
            new CarFeature { Id = 366, CarId = 21, FeatureId = 36 },
            new CarFeature { Id = 367, CarId = 21, FeatureId = 46 },
            new CarFeature { Id = 368, CarId = 21, FeatureId = 42 },
            new CarFeature { Id = 369, CarId = 21, FeatureId = 43 },
            new CarFeature { Id = 370, CarId = 21, FeatureId = 44 },
            new CarFeature { Id = 371, CarId = 21, FeatureId = 49 },
            new CarFeature { Id = 372, CarId = 21, FeatureId = 50 },
            new CarFeature { Id = 373, CarId = 21, FeatureId = 25 },


            new CarFeature { Id = 374, CarId = 22, FeatureId = 1 },
            new CarFeature { Id = 375, CarId = 22, FeatureId = 3 },
            new CarFeature { Id = 376, CarId = 22, FeatureId = 5 },
            new CarFeature { Id = 377, CarId = 22, FeatureId = 6 },
            new CarFeature { Id = 378, CarId = 22, FeatureId = 7 },
            new CarFeature { Id = 379, CarId = 22, FeatureId = 9 },
            new CarFeature { Id = 380, CarId = 22, FeatureId = 17 },
            new CarFeature { Id = 381, CarId = 22, FeatureId = 19 },
            new CarFeature { Id = 382, CarId = 22, FeatureId = 23 },
            new CarFeature { Id = 383, CarId = 22, FeatureId = 28 }
            );
           
            base.OnModelCreating(modelBuilder);
        }
    }
}
