using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Localization;
using Microsoft.EntityFrameworkCore;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RentACar.DataAccess
{
    public class RentACarDbContext:IdentityDbContext<IdentityUser>
    {
        public RentACarDbContext(DbContextOptions<RentACarDbContext> options) : base(options) { }   
        public DbSet<Car> Cars { get; set; }
        public DbSet<CType> Types { get; set; }
        public DbSet<CarType> CarsTypes { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<CarFeature> CarsFeatures { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<ClassOfCar> ClassOfCars { get; set; }
        public DbSet<Customer>Customers { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<CarCompany>CarCompanies { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {



            modelBuilder.Entity<Reservation>()
    .HasOne(r => r.Customer)
    .WithMany(c => c.Reservations)
    .HasForeignKey(r => r.CustomerId)
    .OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<Customer>().HasOne(c => c.User)
                .WithOne()
                .HasForeignKey<Customer>(c => c.UserId).OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<CarCompany>()
    .HasOne(c => c.User)
    .WithOne(u => u.CarCompany)
    .HasForeignKey<CarCompany>(c => c.UserId)
    .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<ClassOfCar>().HasData(
new ClassOfCar { Id = 1, Name = "Economy" },
new ClassOfCar { Id = 2, Name = "Luxury" },
new ClassOfCar { Id = 3, Name = "Sport" },
new ClassOfCar { Id = 4, Name = "Business" },
new ClassOfCar { Id = 5, Name = "Electric" },
new ClassOfCar { Id = 6, Name = "Standard" },
new ClassOfCar { Id = 7, Name = "Retro" }

);
            modelBuilder.Entity<CarCompany>().HasData(
new CarCompany { Id = 1, Name = "Dubai Luxury Cars", Description = "Luxury and sports car rentals in Dubai.", City = "Dubai", Country = "UAE", Address = "Sheikh Zayed Road, Dubai" },
new CarCompany { Id = 2, Name = "Speedy Drive Car Rental", Description = "Affordable and premium car rental services.", City = "Dubai", Country = "UAE", Address = "Al Barsha, Dubai" },
new CarCompany { Id = 3, Name = "Prestige Exotic Car Rental", Description = "Exclusive supercar rentals for special occasions.", City = "Dubai", Country = "UAE", Address = "Business Bay, Dubai" },
new CarCompany { Id = 4, Name = "Quick Lease Car Rental", Description = "Budget-friendly car rental options.", City = "Dubai", Country = "UAE", Address = "Deira, Dubai" },
new CarCompany { Id = 5, Name = "OneClickDrive", Description = "Wide selection of vehicles from economy to luxury.", City = "Dubai", Country = "UAE", Address = "Downtown Dubai", }
);
            modelBuilder.Entity<Car>().HasData(
  new Car { Id = 1, Brand = "Toyota", Model = "Corolla", Gearbox = "Automatic", Year = 2021, PricePerDay = 80, PricePerWeek = 450, MileageLimitForDay = 150, MileageLimitForWeek = 1000, AdditionalMileageCharge = 0.2, EngineCapacity = 1.6, Color = "White", Available = true, Description = "Compact and fuel-efficient", ClassOfCarId = 1, DriveTrain = "Front", HorsePower = 122, ZeroToHundred = 10.8, TopSpeed = 185, CarCompanyId = 5 },
 new Car { Id = 2, Brand = "Honda", Model = "Civic", Gearbox = "Manual", Year = 2022, PricePerDay = 140, PricePerWeek = 600, MileageLimitForDay = 200, MileageLimitForWeek = 1200, AdditionalMileageCharge = 0.25, EngineCapacity = 1.5, Color = "Black", Available = true, Description = "Sporty and reliable", ClassOfCarId = 6, DriveTrain = "Front", HorsePower = 205, ZeroToHundred = 7.3, TopSpeed = 170, CarCompanyId = 5 },
 new Car { Id = 3, Brand = "Ford", Model = "Mustang", Gearbox = "Automatic", Year = 2020, PricePerDay = 200, PricePerWeek = 910, MileageLimitForDay = 250, MileageLimitForWeek = 1500, AdditionalMileageCharge = 0.22, EngineCapacity = 2.3, Color = "Dark Gray", Available = true, Description = "Comfortable and stylish", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 317, ZeroToHundred = 5.8, TopSpeed = 250, CarCompanyId = 1 },
 new Car { Id = 4, Brand = "BMW", Model = "420", Gearbox = "Automatic", Year = 2022, PricePerDay = 250, PricePerWeek = 1000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 0.5, EngineCapacity = 2.0, Color = "Gray", Available = true, Description = "Luxury and performance", ClassOfCarId = 2, DriveTrain = "Rear", HorsePower = 190, ZeroToHundred = 7.1, TopSpeed = 240, CarCompanyId = 1 },
 new Car { Id = 5, Brand = "Mercedes-Benz", Model = "C-Class", Gearbox = "Automatic", Year = 2021, PricePerDay = 210, PricePerWeek = 850, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 0.55, EngineCapacity = 3.0, Color = "Red", Available = true, Description = "Premium luxury", ClassOfCarId = 2, DriveTrain = "Rear", HorsePower = 258, ZeroToHundred = 6.2, TopSpeed = 250, CarCompanyId = 1 },
 new Car { Id = 6, Brand = "Audi", Model = "R8 Spyder", Gearbox = "Automatic", Year = 2021, PricePerDay = 750, PricePerWeek = 6400, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 1.0, EngineCapacity = 5.2, Color = "Green", Available = true, Description = "High-performance sports car", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 570, ZeroToHundred = 3.8, TopSpeed = 327, CarCompanyId = 2 },
 new Car { Id = 7, Brand = "Lamborghini", Model = "Huracan", Gearbox = "Automatic", Year = 2023, PricePerDay = 1700, PricePerWeek = 9000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 1.5, EngineCapacity = 5.2, Color = "Black", Available = true, Description = "Exotic sports car", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 640, ZeroToHundred = 3.0, TopSpeed = 310, CarCompanyId = 2 },
 new Car { Id = 8, Brand = "Porsche", Model = "911 GT3", Gearbox = "Automatic", Year = 2023, PricePerDay = 1400, PricePerWeek = 8400, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 1.3, EngineCapacity = 3.0, Color = "Silver", Available = true, Description = "Luxury sports car", ClassOfCarId = 3, DriveTrain = "Full Wheels", HorsePower = 450, ZeroToHundred = 3.8, TopSpeed = 304, CarCompanyId = 1 },
 new Car { Id = 9, Brand = "Tesla", Model = "Model S Plaid", Gearbox = "Automatic", Year = 2023, PricePerDay = 350, PricePerWeek = 2100, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 1.0, EngineCapacity = 0.0, Color = "White", Available = true, Description = "Electric luxury sedan", ClassOfCarId = 5, DriveTrain = "Rear", HorsePower = 1020, ZeroToHundred = 2.1, TopSpeed = 322, CarCompanyId = 3 },
 new Car { Id = 10, Brand = "Ferrari", Model = "F8 Spider", Gearbox = "Automatic", Year = 2022, PricePerDay = 2300, PricePerWeek = 10000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 2.0, EngineCapacity = 3.9, Color = "Red", Available = true, Description = "Iconic Italian sports car", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 720, ZeroToHundred = 2.9, TopSpeed = 340, CarCompanyId = 3 },
 new Car { Id = 11, Brand = "Rolls-Royce", Model = "Phantom", Gearbox = "Automatic", Year = 2021, PricePerDay = 1000, PricePerWeek = 7000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.0, EngineCapacity = 6.8, Color = "Black", Available = true, Description = "Ultimate luxury car", ClassOfCarId = 4, DriveTrain = "Rear", HorsePower = 571, ZeroToHundred = 5.4, TopSpeed = 250, CarCompanyId = 3 },
 new Car { Id = 12, Brand = "Bentley", Model = "Continental GT-GTC", Gearbox = "Automatic", Year = 2023, PricePerDay = 1300, PricePerWeek = 7600, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.5, EngineCapacity = 6.0, Color = "Black", Available = true, Description = "Grand luxury tourer", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 659, ZeroToHundred = 3.7, TopSpeed = 335, CarCompanyId = 1 },
 new Car { Id = 13, Brand = "McLaren", Model = "720S", Gearbox = "Automatic", Year = 2023, PricePerDay = 1700, PricePerWeek = 8000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 2.0, EngineCapacity = 4.0, Color = "Blue", Available = true, Description = "Exquisite British engineering", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 720, ZeroToHundred = 2.9, TopSpeed = 341, CarCompanyId = 2 },
 new Car { Id = 14, Brand = "Aston Martin", Model = "DBX", Gearbox = "Automatic", Year = 2023, PricePerDay = 600, PricePerWeek = 3600, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.0, EngineCapacity = 4.0, Color = "Black", Available = true, Description = "Luxury British SUV", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 550, ZeroToHundred = 4.5, TopSpeed = 291, CarCompanyId = 2 },
 new Car { Id = 15, Brand = "Lexus", Model = "LX", Gearbox = "Automatic", Year = 2023, PricePerDay = 500, PricePerWeek = 3000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.5, Color = "Silver", Available = true, Description = "Sophisticated luxury SUV", ClassOfCarId = 2, DriveTrain = "Full Wheels", HorsePower = 415, ZeroToHundred = 6.8, TopSpeed = 210, CarCompanyId = 4 },
 new Car { Id = 16, Brand = "Mercedes-Benz", Model = "AMG GT", Gearbox = "Automatic", Year = 2022, PricePerDay = 2500, PricePerWeek = 1100, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 2.2, EngineCapacity = 4.0, Color = "Orange", Available = true, Description = "German engineering excellence", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 730, ZeroToHundred = 3.2, TopSpeed = 322, CarCompanyId = 2 },
 new Car { Id = 17, Brand = "Audi", Model = "Q8", Gearbox = "Automatic", Year = 2021, PricePerDay = 400, PricePerWeek = 2300, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.0, EngineCapacity = 3.0, Color = "Orange", Available = true, Description = "Luxury SUV", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 340, ZeroToHundred = 5.9, TopSpeed = 250, CarCompanyId = 5 },
 new Car { Id = 18, Brand = "BMW", Model = "M4", Gearbox = "Automatic", Year = 2023, PricePerDay = 700, PricePerWeek = 4000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.5, EngineCapacity = 3.0, Color = "Yellow", Available = true, Description = "Sporty and agile", ClassOfCarId = 3, DriveTrain = "Full Wheels", HorsePower = 510, ZeroToHundred = 3.7, TopSpeed = 250, CarCompanyId = 2 },
 new Car { Id = 19, Brand = "Toyota", Model = "Camry", Gearbox = "Automatic", Year = 2021, PricePerDay = 130, PricePerWeek = 670, MileageLimitForDay = 200, MileageLimitForWeek = 1200, AdditionalMileageCharge = 0.25, EngineCapacity = 2.5, Color = "Red", Available = true, Description = "Dependable sedan", ClassOfCarId = 6, DriveTrain = "Rear", HorsePower = 182, ZeroToHundred = 9.9, TopSpeed = 210, CarCompanyId = 2 },
 new Car { Id = 20, Brand = "Tesla", Model = "Cybertruck", Gearbox = "Automatic", Year = 2024, PricePerDay = 2000, PricePerWeek = 12000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 0.0, Color = "Black", Available = true, Description = "Sophisticated luxury SUV", ClassOfCarId = 5, DriveTrain = "Full Wheels", HorsePower = 845, ZeroToHundred = 2.7, TopSpeed = 210, CarCompanyId = 3 },
 new Car { Id = 21, Brand = "Land Rover", Model = "Range Rover", Gearbox = "Automatic", Year = 2023, PricePerDay = 1200, PricePerWeek = 7000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.0, Color = "Black", Available = true, Description = "Sophisticated luxury SUV", ClassOfCarId = 4, DriveTrain = "Full Wheels", HorsePower = 360, ZeroToHundred = 6.9, TopSpeed = 209, CarCompanyId = 2 },
 new Car { Id = 22, Brand = "Toyota", Model = "Supra", Gearbox = "Automatic", Year = 2022, PricePerDay = 220, PricePerWeek = 1100, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.0, Color = "White", Available = true, Description = "Sporty and agile", ClassOfCarId = 3, DriveTrain = "Rear", HorsePower = 340, ZeroToHundred = 4.4, TopSpeed = 262, CarCompanyId = 1 }
 );
            modelBuilder.Entity<Feature>().HasData(
      new Feature { Id = 1, NameOfFeatures = "Air Conditioning" },
      new Feature { Id = 2, NameOfFeatures = "Heated Seats" },
      new Feature { Id = 3, NameOfFeatures = "Bluetooth Connectivity" },
      new Feature { Id = 4, NameOfFeatures = "Navigation System" },
      new Feature { Id = 5, NameOfFeatures = "Cruise Control" },
      new Feature { Id = 6, NameOfFeatures = "Rearview Camera" },
      new Feature { Id = 7, NameOfFeatures = "Lane Departure Warning" },
      new Feature { Id = 8, NameOfFeatures = "Adaptive Headlights" },
      new Feature { Id = 9, NameOfFeatures = "Blind Spot Detection" },
      new Feature { Id = 10, NameOfFeatures = "Automatic Parking" },
      new Feature { Id = 11, NameOfFeatures = "Push-Button Start" },
      new Feature { Id = 12, NameOfFeatures = "Wireless Charging" },
      new Feature { Id = 13, NameOfFeatures = "Panoramic Sunroof" },
      new Feature { Id = 14, NameOfFeatures = "Power Adjustable Seats" },
      new Feature { Id = 15, NameOfFeatures = "Backup Sensors" },
      new Feature { Id = 16, NameOfFeatures = "Heated Steering Wheel" },
      new Feature { Id = 17, NameOfFeatures = "Keyless Entry" },
      new Feature { Id = 18, NameOfFeatures = "Surround-View Camera" },
      new Feature { Id = 19, NameOfFeatures = "Remote Start" },
      new Feature { Id = 20, NameOfFeatures = "Apple CarPlay" },
      new Feature { Id = 21, NameOfFeatures = "Android Auto" },
      new Feature { Id = 22, NameOfFeatures = "Rear Cross Traffic Alert" },
      new Feature { Id = 23, NameOfFeatures = "Adaptive Cruise Control" },
      new Feature { Id = 24, NameOfFeatures = "Heads-Up Display (HUD)" },
      new Feature { Id = 25, NameOfFeatures = "Ambient Lighting" },
      new Feature { Id = 26, NameOfFeatures = "Wireless Apple CarPlay" },
      new Feature { Id = 27, NameOfFeatures = "Power Tailgate" },
      new Feature { Id = 28, NameOfFeatures = "Automatic Emergency Braking" },
      new Feature { Id = 29, NameOfFeatures = "Traffic Sign Recognition" },
      new Feature { Id = 30, NameOfFeatures = "Rain-Sensing Wipers" },
      new Feature { Id = 31, NameOfFeatures = "Dual-Zone Climate Control" },
      new Feature { Id = 32, NameOfFeatures = "Power Folding Mirrors" },
      new Feature { Id = 33, NameOfFeatures = "Lane Keeping Assist" },
      new Feature { Id = 34, NameOfFeatures = "Electric Power Steering" },
      new Feature { Id = 35, NameOfFeatures = "Turbocharged Engine" },
      new Feature { Id = 36, NameOfFeatures = "Carbon Fiber Trim" },
      new Feature { Id = 37, NameOfFeatures = "Active Noise Cancellation" },
      new Feature { Id = 38, NameOfFeatures = "All-Wheel Drive" },
      new Feature { Id = 39, NameOfFeatures = "Front Parking Sensors" },
      new Feature { Id = 40, NameOfFeatures = "Sport Mode" },
      new Feature { Id = 41, NameOfFeatures = "Wireless Smartphone Charging" },
      new Feature { Id = 42, NameOfFeatures = "Massaging Seats" },
      new Feature { Id = 43, NameOfFeatures = "Self-Healing Paint" },
      new Feature { Id = 44, NameOfFeatures = "Night Vision" },
      new Feature { Id = 45, NameOfFeatures = "Active Rear Spoiler" },
      new Feature { Id = 46, NameOfFeatures = "Heads-Up Display with Navigation" },
      new Feature { Id = 47, NameOfFeatures = "Wireless Internet Access" },
      new Feature { Id = 48, NameOfFeatures = "Active Suspension" },
      new Feature { Id = 49, NameOfFeatures = "Power Adjustable Steering Wheel" },
      new Feature { Id = 50, NameOfFeatures = "Touchscreen Control Panel" }
  );

            modelBuilder.Entity<Image>().HasData(
                new Image { Id = 1, Url = "/images/toyota-corolla1.jpg", CarId = 1 },
                new Image { Id = 2, Url = "/images/toyota-corolla2.jpg", CarId = 1 },
                new Image { Id = 3, Url = "/images/toyota-corolla3.jpg", CarId = 1 },
                new Image { Id = 4, Url = "/images/toyota-corolla4.jpg", CarId = 1 },
                new Image { Id = 5, Url = "/images/honda-civic1.png", CarId = 2 },
                new Image { Id = 6, Url = "/images/honda-civic2.png", CarId = 2 },
                new Image { Id = 7, Url = "/images/honda-civic3.png", CarId = 2 },
                new Image { Id = 8, Url = "/images/honda-civic4.png", CarId = 2 },
                new Image { Id = 9, Url = "/images/bmw-420i1.png", CarId = 4 },
                new Image { Id = 10, Url = "/images/bmw-420i2.png", CarId = 4 },
                new Image { Id = 11, Url = "/images/bmw-420i7.png", CarId = 4 },
                new Image { Id = 12, Url = "/images/bmw-420i3.png", CarId = 4 },
                new Image { Id = 13, Url = "/images/bmw-420i4.png", CarId = 4 },
                new Image { Id = 14, Url = "/images/bmw-420i5.png", CarId = 4 },
                new Image { Id = 15, Url = "/images/bmw-420i6.png", CarId = 4 },
                new Image { Id = 16, Url = "/images/c300-1.webp", CarId = 5 },
                new Image { Id = 17, Url = "/images/c300-2.webp", CarId = 5 },
                new Image { Id = 18, Url = "/images/c300-3.webp", CarId = 5 },
                new Image { Id = 19, Url = "/images/c300-4.webp", CarId = 5 },
                new Image { Id = 20, Url = "/images/c300-5.webp", CarId = 5 },
                new Image { Id = 21, Url = "/images/c300-6.webp", CarId = 5 },
                new Image { Id = 22, Url = "/images/ford-mustang-1.webp", CarId = 3 },
                new Image { Id = 23, Url = "/images/ford-mustang-2.webp", CarId = 3 },
                new Image { Id = 24, Url = "/images/ford-mustang-3.webp", CarId = 3 },
                new Image { Id = 25, Url = "/images/ford-mustang-4.webp", CarId = 3 },
                new Image { Id = 26, Url = "/images/ford-mustang-5.webp", CarId = 3 },
                new Image { Id = 27, Url = "/images/ford-mustang-6.webp", CarId = 3 },
                new Image { Id = 28, Url = "/images/ford-mustang-7.webp", CarId = 3 },
                new Image { Id = 29, Url = "/images/ford-mustang-8.webp", CarId = 3 },
                new Image { Id = 30, Url = "/images/audi-r8-1.jpg", CarId = 6 },
                new Image { Id = 31, Url = "/images/audi-r8-2.jpg", CarId = 6 },
                new Image { Id = 32, Url = "/images/audi-r8-3.jpg", CarId = 6 },
                new Image { Id = 33, Url = "/images/audi-r8-4.jpg", CarId = 6 },
                new Image { Id = 34, Url = "/images/audi-r8-5.jpg", CarId = 6 },
                new Image { Id = 35, Url = "/images/audi-r8-6.jpg", CarId = 6 },
                new Image { Id = 36, Url = "/images/audi-r8-7.jpg", CarId = 6 },
                new Image { Id = 37, Url = "/images/audi-r8-8.jpg", CarId = 6 },
                new Image { Id = 38, Url = "/images/lambo-hur-1.jpg", CarId = 7 },
                new Image { Id = 39, Url = "/images/lambo-hur-2.jpg", CarId = 7 },
                new Image { Id = 40, Url = "/images/lambo-hur-3.jpg", CarId = 7 },
                new Image { Id = 41, Url = "/images/lambo-hur-4.jpg", CarId = 7 },
                new Image { Id = 42, Url = "/images/lambo-hur-5.jpg", CarId = 7 },
                new Image { Id = 43, Url = "/images/porsche-gt3-1.webp", CarId = 8 },
                new Image { Id = 44, Url = "/images/porsche-gt3-2.webp", CarId = 8 },
                new Image { Id = 45, Url = "/images/porsche-gt3-3.webp", CarId = 8 },
                new Image { Id = 46, Url = "/images/porsche-gt3-4.webp", CarId = 8 },
                new Image { Id = 47, Url = "/images/porsche-gt3-5.webp", CarId = 8 },
                new Image { Id = 48, Url = "/images/porsche-gt3-6.webp", CarId = 8 },
                new Image { Id = 49, Url = "/images/porsche-gt3-7.webp", CarId = 8 },
                new Image { Id = 50, Url = "/images/porsche-gt3-8.webp", CarId = 8 },
                new Image { Id = 51, Url = "/images/tesla-s-1.webp", CarId = 9 },
                new Image { Id = 52, Url = "/images/tesla-s-2.webp", CarId = 9 },
                new Image { Id = 53, Url = "/images/tesla-s-3.webp", CarId = 9 },
                new Image { Id = 54, Url = "/images/tesla-s-4.webp", CarId = 9 },
                new Image { Id = 55, Url = "/images/tesla-s-5.webp", CarId = 9 },
                new Image { Id = 56, Url = "/images/tesla-s-6.webp", CarId = 9 },
                new Image { Id = 57, Url = "/images/ferrari-f-1.webp", CarId = 10 },
                new Image { Id = 58, Url = "/images/ferrari-f-2.webp", CarId = 10 },
                new Image { Id = 59, Url = "/images/ferrari-f-3.webp", CarId = 10 },
                new Image { Id = 60, Url = "/images/ferrari-f-4.webp", CarId = 10 },
                new Image { Id = 61, Url = "/images/ferrari-f-5.webp", CarId = 10 },
                new Image { Id = 62, Url = "/images/ferrari-f-6.webp", CarId = 10 },
                new Image { Id = 63, Url = "/images/ferrari-f-7.webp", CarId = 10 },
                new Image { Id = 64, Url = "/images/ferrari-f-8.webp", CarId = 10 },
                new Image { Id = 65, Url = "/images/phanthom-1.webp", CarId = 11 },
                new Image { Id = 66, Url = "/images/phanthom-2.webp", CarId = 11 },
                new Image { Id = 67, Url = "/images/phanthom-3.webp", CarId = 11 },
                new Image { Id = 68, Url = "/images/phanthom-4.webp", CarId = 11 },
                new Image { Id = 69, Url = "/images/phanthom-5.webp", CarId = 11 },
                new Image { Id = 70, Url = "/images/phanthom-6.webp", CarId = 11 },
                new Image { Id = 71, Url = "/images/phanthom-7.webp", CarId = 11 },
                new Image { Id = 72, Url = "/images/phanthom-8.webp", CarId = 11 },
                new Image { Id = 73, Url = "/images/phanthom-9.webp", CarId = 11 },
                new Image { Id = 74, Url = "/images/phanthom-10.webp", CarId = 11 },
                new Image { Id = 75, Url = "/images/phanthom-11.webp", CarId = 11 },
                new Image { Id = 76, Url = "/images/bentley-continental-gt-1.webp", CarId = 12 },
                new Image { Id = 77, Url = "/images/bentley-continental-gt-2.webp", CarId = 12 },
                new Image { Id = 78, Url = "/images/bentley-continental-gt-3.webp", CarId = 12 },
                new Image { Id = 79, Url = "/images/bentley-continental-gt-4.webp", CarId = 12 },
                new Image { Id = 80, Url = "/images/bentley-continental-gt-5.webp", CarId = 12 },
                new Image { Id = 81, Url = "/images/bentley-continental-gt-6.webp", CarId = 12 },
                new Image { Id = 82, Url = "/images/bentley-continental-gt-7.webp", CarId = 12 },
                new Image { Id = 83, Url = "/images/bentley-continental-gt-8.webp", CarId = 12 },
                new Image { Id = 84, Url = "/images/bentley-continental-gt-9.webp", CarId = 12 },
                new Image { Id = 85, Url = "/images/bentley-continental-gt-10.webp", CarId = 12 },
                new Image { Id = 86, Url = "/images/bentley-continental-gt-11.webp", CarId = 12 },
                new Image { Id = 87, Url = "/images/bentley-continental-gt-12.webp", CarId = 12 },
                new Image { Id = 88, Url = "/images/mc-720s-1.webp", CarId = 13 },
                new Image { Id = 89, Url = "/images/mc-720s-2.webp", CarId = 13 },
                new Image { Id = 90, Url = "/images/mc-720s-3.webp", CarId = 13 },
                new Image { Id = 91, Url = "/images/mc-720s-4.webp", CarId = 13 },
                new Image { Id = 92, Url = "/images/mc-720s-5.webp", CarId = 13 },
                new Image { Id = 93, Url = "/images/mc-720s-6.webp", CarId = 13 },
                new Image { Id = 94, Url = "/images/mc-720s-7.webp", CarId = 13 },
                new Image { Id = 95, Url = "/images/aston-dbx-1.webp", CarId = 14 },
                new Image { Id = 96, Url = "/images/aston-dbx-2.webp", CarId = 14 },
                new Image { Id = 97, Url = "/images/aston-dbx-3.webp", CarId = 14 },
                new Image { Id = 98, Url = "/images/aston-dbx-4.webp", CarId = 14 },
                new Image { Id = 99, Url = "/images/aston-dbx-5.webp", CarId = 14 },
                new Image { Id = 100, Url = "/images/aston-dbx-6.webp", CarId = 14 },
                new Image { Id = 101, Url = "/images/aston-dbx-7.webp", CarId = 14 },
                new Image { Id = 102, Url = "/images/aston-dbx-8.webp", CarId = 14 },
                new Image { Id = 103, Url = "/images/lexus-lx-1.webp", CarId = 15 },
                new Image { Id = 104, Url = "/images/lexus-lx-2.webp", CarId = 15 },
                new Image { Id = 105, Url = "/images/lexus-lx-3.webp", CarId = 15 },
                new Image { Id = 106, Url = "/images/lexus-lx-4.webp", CarId = 15 },
                new Image { Id = 107, Url = "/images/lexus-lx-5.webp", CarId = 15 },
                new Image { Id = 108, Url = "/images/lexus-lx-6.webp", CarId = 15 },
                new Image { Id = 109, Url = "/images/lexus-lx-7.webp", CarId = 15 },
                new Image { Id = 110, Url = "/images/amg-gt-1.webp", CarId = 16 },
                new Image { Id = 111, Url = "/images/amg-gt-2.webp", CarId = 16 },
                new Image { Id = 112, Url = "/images/amg-gt-3.webp", CarId = 16 },
                new Image { Id = 113, Url = "/images/amg-gt-4.webp", CarId = 16 },
                new Image { Id = 114, Url = "/images/amg-gt-5.webp", CarId = 16 },
                new Image { Id = 115, Url = "/images/amg-gt-6.webp", CarId = 16 },
                new Image { Id = 116, Url = "/images/amg-gt-7.webp", CarId = 16 },
                new Image { Id = 117, Url = "/images/amg-gt-8.webp", CarId = 16 },
                new Image { Id = 118, Url = "/images/audi-q8-1.webp", CarId = 17 },
                new Image { Id = 119, Url = "/images/audi-q8-2.webp", CarId = 17 },
                new Image { Id = 120, Url = "/images/audi-q8-3.webp", CarId = 17 },
                new Image { Id = 121, Url = "/images/audi-q8-4.webp", CarId = 17 },
                new Image { Id = 122, Url = "/images/audi-q8-5.webp", CarId = 17 },
                new Image { Id = 123, Url = "/images/audi-q8-6.webp", CarId = 17 },
                new Image { Id = 124, Url = "/images/audi-q8-7.webp", CarId = 17 },
                new Image { Id = 125, Url = "/images/audi-q8-8.webp", CarId = 17 },
                new Image { Id = 126, Url = "/images/audi-q8-9.webp", CarId = 17 },
                new Image { Id = 127, Url = "/images/bmw-m4-1.webp", CarId = 18 },
                new Image { Id = 128, Url = "/images/bmw-m4-2.webp", CarId = 18 },
                new Image { Id = 129, Url = "/images/bmw-m4-3.webp", CarId = 18 },
                new Image { Id = 130, Url = "/images/bmw-m4-4.webp", CarId = 18 },
                new Image { Id = 131, Url = "/images/bmw-m4-5.webp", CarId = 18 },
                new Image { Id = 132, Url = "/images/bmw-m4-6.webp", CarId = 18 },
                new Image { Id = 133, Url = "/images/camry-1.webp", CarId = 19 },
                new Image { Id = 134, Url = "/images/camry-2.webp", CarId = 19 },
                new Image { Id = 135, Url = "/images/camry-3.webp", CarId = 19 },
                new Image { Id = 136, Url = "/images/camry-4.webp", CarId = 19 },
                new Image { Id = 137, Url = "/images/camry-5.webp", CarId = 19 },
                new Image { Id = 138, Url = "/images/camry-6.webp", CarId = 19 },
                new Image { Id = 139, Url = "/images/camry-7.webp", CarId = 19 },
                new Image { Id = 140, Url = "/images/cybertruck-1.webp", CarId = 20 },
                new Image { Id = 141, Url = "/images/cybertruck-2.webp", CarId = 20 },
                new Image { Id = 142, Url = "/images/cybertruck-3.webp", CarId = 20 },
                new Image { Id = 143, Url = "/images/cybertruck-4.webp", CarId = 20 },
                new Image { Id = 144, Url = "/images/cybertruck-5.webp", CarId = 20 },
                new Image { Id = 145, Url = "/images/rover-1.webp", CarId = 21 },
                new Image { Id = 146, Url = "/images/rover-2.webp", CarId = 21 },
                new Image { Id = 147, Url = "/images/rover-3.webp", CarId = 21 },
                new Image { Id = 148, Url = "/images/rover-4.webp", CarId = 21 },
                new Image { Id = 149, Url = "/images/rover-5.webp", CarId = 21 },
                new Image { Id = 150, Url = "/images/rover-6.webp", CarId = 21 },
                new Image { Id = 151, Url = "/images/rover-7.webp", CarId = 21 },
                new Image { Id = 152, Url = "/images/rover-8.webp", CarId = 21 },
                new Image { Id = 153, Url = "/images/rover-9.webp", CarId = 21 },
                new Image { Id = 154, Url = "/images/toyota-supra-1.webp", CarId = 22 },
                new Image { Id = 155, Url = "/images/toyota-supra-2.webp", CarId = 22 },
                new Image { Id = 156, Url = "/images/toyota-supra-3.webp", CarId = 22 },
                new Image { Id = 157, Url = "/images/toyota-supra-4.webp", CarId = 22 },
                new Image { Id = 158, Url = "/images/toyota-supra-5.webp", CarId = 22 },
                new Image { Id = 159, Url = "/images/toyota-supra-6.webp", CarId = 22 }
                );
            modelBuilder.Entity<CarFeature>().HasData(
            new CarFeature { Id = 1, CarId = 1, FeatureId = 1 },
            new CarFeature { Id = 2, CarId = 1, FeatureId = 3 },
            new CarFeature { Id = 3, CarId = 1, FeatureId = 5 },
            new CarFeature { Id = 4, CarId = 1, FeatureId = 6 },
            new CarFeature { Id = 5, CarId = 1, FeatureId = 7 },
            new CarFeature { Id = 6, CarId = 1, FeatureId = 23 },

            new CarFeature { Id = 7, CarId = 2, FeatureId = 1 },
            new CarFeature { Id = 8, CarId = 2, FeatureId = 3 },
            new CarFeature { Id = 9, CarId = 2, FeatureId = 5 },
            new CarFeature { Id = 10, CarId = 2, FeatureId = 6 },
            new CarFeature { Id = 11, CarId = 2, FeatureId = 7 },
            new CarFeature { Id = 12, CarId = 2, FeatureId = 9 },
            new CarFeature { Id = 13, CarId = 2, FeatureId = 17 },
            new CarFeature { Id = 14, CarId = 2, FeatureId = 19 },
            new CarFeature { Id = 15, CarId = 2, FeatureId = 20 },
            new CarFeature { Id = 16, CarId = 2, FeatureId = 21 },
            new CarFeature { Id = 17, CarId = 2, FeatureId = 23 },
            new CarFeature { Id = 18, CarId = 2, FeatureId = 28 },
            new CarFeature { Id = 19, CarId = 2, FeatureId = 30 },
            new CarFeature { Id = 20, CarId = 2, FeatureId = 31 },
            new CarFeature { Id = 21, CarId = 2, FeatureId = 33 },
            new CarFeature { Id = 22, CarId = 2, FeatureId = 38 },

            new CarFeature { Id = 23, CarId = 3, FeatureId = 1 },
            new CarFeature { Id = 24, CarId = 3, FeatureId = 3 },
            new CarFeature { Id = 25, CarId = 3, FeatureId = 5 },
            new CarFeature { Id = 26, CarId = 3, FeatureId = 6 },
            new CarFeature { Id = 27, CarId = 3, FeatureId = 7 },
            new CarFeature { Id = 28, CarId = 3, FeatureId = 9 },
            new CarFeature { Id = 29, CarId = 3, FeatureId = 17 },
            new CarFeature { Id = 30, CarId = 3, FeatureId = 19 },
            new CarFeature { Id = 31, CarId = 3, FeatureId = 20 },
            new CarFeature { Id = 32, CarId = 3, FeatureId = 21 },
            new CarFeature { Id = 33, CarId = 3, FeatureId = 28 },
            new CarFeature { Id = 34, CarId = 3, FeatureId = 33 },
            new CarFeature { Id = 35, CarId = 3, FeatureId = 40 },
            new CarFeature { Id = 36, CarId = 3, FeatureId = 42 },
            new CarFeature { Id = 37, CarId = 3, FeatureId = 45 },
            new CarFeature { Id = 38, CarId = 3, FeatureId = 46 },

            new CarFeature { Id = 39, CarId = 4, FeatureId = 1 },
            new CarFeature { Id = 40, CarId = 4, FeatureId = 3 },
            new CarFeature { Id = 41, CarId = 4, FeatureId = 5 },
            new CarFeature { Id = 42, CarId = 4, FeatureId = 6 },
            new CarFeature { Id = 43, CarId = 4, FeatureId = 7 },
            new CarFeature { Id = 44, CarId = 4, FeatureId = 9 },
            new CarFeature { Id = 45, CarId = 4, FeatureId = 17 },
            new CarFeature { Id = 46, CarId = 4, FeatureId = 19 },
            new CarFeature { Id = 47, CarId = 4, FeatureId = 20 },
            new CarFeature { Id = 48, CarId = 4, FeatureId = 21 },
            new CarFeature { Id = 49, CarId = 4, FeatureId = 23 },
            new CarFeature { Id = 50, CarId = 4, FeatureId = 28 },
            new CarFeature { Id = 51, CarId = 4, FeatureId = 30 },
            new CarFeature { Id = 52, CarId = 4, FeatureId = 31 },
            new CarFeature { Id = 53, CarId = 4, FeatureId = 33 },
            new CarFeature { Id = 54, CarId = 4, FeatureId = 34 },
            new CarFeature { Id = 55, CarId = 4, FeatureId = 36 },
            new CarFeature { Id = 56, CarId = 4, FeatureId = 40 },
            new CarFeature { Id = 57, CarId = 4, FeatureId = 41 },
            new CarFeature { Id = 58, CarId = 4, FeatureId = 45 },
            new CarFeature { Id = 59, CarId = 4, FeatureId = 47 },
            new CarFeature { Id = 60, CarId = 4, FeatureId = 33 },
            new CarFeature { Id = 61, CarId = 4, FeatureId = 34 },

            new CarFeature { Id = 62, CarId = 5, FeatureId = 1 },
            new CarFeature { Id = 63, CarId = 5, FeatureId = 3 },
            new CarFeature { Id = 64, CarId = 5, FeatureId = 5 },
            new CarFeature { Id = 65, CarId = 5, FeatureId = 6 },
            new CarFeature { Id = 66, CarId = 5, FeatureId = 7 },
            new CarFeature { Id = 67, CarId = 5, FeatureId = 9 },
            new CarFeature { Id = 68, CarId = 5, FeatureId = 17 },
            new CarFeature { Id = 69, CarId = 5, FeatureId = 19 },
            new CarFeature { Id = 70, CarId = 5, FeatureId = 20 },
            new CarFeature { Id = 71, CarId = 5, FeatureId = 21 },
            new CarFeature { Id = 72, CarId = 5, FeatureId = 23 },
            new CarFeature { Id = 73, CarId = 5, FeatureId = 28 },
            new CarFeature { Id = 74, CarId = 5, FeatureId = 30 },
            new CarFeature { Id = 75, CarId = 5, FeatureId = 31 },
            new CarFeature { Id = 76, CarId = 5, FeatureId = 33 },
            new CarFeature { Id = 77, CarId = 5, FeatureId = 34 },
            new CarFeature { Id = 78, CarId = 5, FeatureId = 40 },
            new CarFeature { Id = 79, CarId = 5, FeatureId = 41 },
            new CarFeature { Id = 80, CarId = 5, FeatureId = 45 },
            new CarFeature { Id = 81, CarId = 5, FeatureId = 47 },


            new CarFeature { Id = 82, CarId = 6, FeatureId = 1 },
            new CarFeature { Id = 83, CarId = 6, FeatureId = 3 },
            new CarFeature { Id = 84, CarId = 6, FeatureId = 5 },
            new CarFeature { Id = 85, CarId = 6, FeatureId = 6 },
            new CarFeature { Id = 86, CarId = 6, FeatureId = 7 },
            new CarFeature { Id = 87, CarId = 6, FeatureId = 9 },
            new CarFeature { Id = 88, CarId = 6, FeatureId = 17 },
            new CarFeature { Id = 89, CarId = 6, FeatureId = 19 },
            new CarFeature { Id = 90, CarId = 6, FeatureId = 20 },
            new CarFeature { Id = 91, CarId = 6, FeatureId = 21 },
            new CarFeature { Id = 92, CarId = 6, FeatureId = 23 },
            new CarFeature { Id = 93, CarId = 6, FeatureId = 28 },
            new CarFeature { Id = 94, CarId = 6, FeatureId = 30 },
            new CarFeature { Id = 95, CarId = 6, FeatureId = 31 },
            new CarFeature { Id = 96, CarId = 6, FeatureId = 33 },
            new CarFeature { Id = 97, CarId = 6, FeatureId = 34 },
            new CarFeature { Id = 98, CarId = 6, FeatureId = 40 },
            new CarFeature { Id = 99, CarId = 6, FeatureId = 41 },
            new CarFeature { Id = 100, CarId = 6, FeatureId = 45 },
            new CarFeature { Id = 101, CarId = 6, FeatureId = 47 },

            new CarFeature { Id = 102, CarId = 7, FeatureId = 1 },
            new CarFeature { Id = 103, CarId = 7, FeatureId = 3 },
            new CarFeature { Id = 104, CarId = 7, FeatureId = 5 },
            new CarFeature { Id = 105, CarId = 7, FeatureId = 6 },
            new CarFeature { Id = 106, CarId = 7, FeatureId = 7 },
            new CarFeature { Id = 107, CarId = 7, FeatureId = 9 },
            new CarFeature { Id = 108, CarId = 7, FeatureId = 17 },
            new CarFeature { Id = 109, CarId = 7, FeatureId = 19 },
            new CarFeature { Id = 110, CarId = 7, FeatureId = 20 },
            new CarFeature { Id = 111, CarId = 7, FeatureId = 23 },
            new CarFeature { Id = 112, CarId = 7, FeatureId = 28 },
            new CarFeature { Id = 113, CarId = 7, FeatureId = 30 },
            new CarFeature { Id = 114, CarId = 7, FeatureId = 31 },
            new CarFeature { Id = 115, CarId = 7, FeatureId = 33 },
            new CarFeature { Id = 116, CarId = 7, FeatureId = 40 },
            new CarFeature { Id = 117, CarId = 7, FeatureId = 41 },
            new CarFeature { Id = 118, CarId = 7, FeatureId = 45 },
            new CarFeature { Id = 119, CarId = 7, FeatureId = 47 },

            new CarFeature { Id = 120, CarId = 8, FeatureId = 1 },
            new CarFeature { Id = 121, CarId = 8, FeatureId = 3 },
            new CarFeature { Id = 122, CarId = 8, FeatureId = 5 },
            new CarFeature { Id = 123, CarId = 8, FeatureId = 6 },
            new CarFeature { Id = 124, CarId = 8, FeatureId = 7 },
            new CarFeature { Id = 125, CarId = 8, FeatureId = 17 },
            new CarFeature { Id = 126, CarId = 8, FeatureId = 20 },
            new CarFeature { Id = 127, CarId = 8, FeatureId = 21 },
            new CarFeature { Id = 128, CarId = 8, FeatureId = 23 },
            new CarFeature { Id = 129, CarId = 8, FeatureId = 28 },
            new CarFeature { Id = 130, CarId = 8, FeatureId = 40 },
            new CarFeature { Id = 131, CarId = 8, FeatureId = 41 },
            new CarFeature { Id = 132, CarId = 8, FeatureId = 45 },
            new CarFeature { Id = 133, CarId = 8, FeatureId = 36 },
            new CarFeature { Id = 134, CarId = 8, FeatureId = 48 },

            new CarFeature { Id = 135, CarId = 9, FeatureId = 1 },
            new CarFeature { Id = 136, CarId = 9, FeatureId = 3 },
            new CarFeature { Id = 137, CarId = 9, FeatureId = 5 },
            new CarFeature { Id = 138, CarId = 9, FeatureId = 6 },
            new CarFeature { Id = 139, CarId = 9, FeatureId = 7 },
            new CarFeature { Id = 140, CarId = 9, FeatureId = 9 },
            new CarFeature { Id = 141, CarId = 9, FeatureId = 17 },
            new CarFeature { Id = 142, CarId = 9, FeatureId = 19 },
            new CarFeature { Id = 143, CarId = 9, FeatureId = 20 },
            new CarFeature { Id = 144, CarId = 9, FeatureId = 21 },
            new CarFeature { Id = 145, CarId = 9, FeatureId = 23 },
            new CarFeature { Id = 146, CarId = 9, FeatureId = 28 },
            new CarFeature { Id = 147, CarId = 9, FeatureId = 30 },
            new CarFeature { Id = 148, CarId = 9, FeatureId = 31 },
            new CarFeature { Id = 149, CarId = 9, FeatureId = 34 },
            new CarFeature { Id = 150, CarId = 9, FeatureId = 40 },
            new CarFeature { Id = 151, CarId = 9, FeatureId = 41 },
            new CarFeature { Id = 152, CarId = 9, FeatureId = 47 },
            new CarFeature { Id = 153, CarId = 9, FeatureId = 48 },

            new CarFeature { Id = 154, CarId = 10, FeatureId = 1 },
            new CarFeature { Id = 155, CarId = 10, FeatureId = 3 },
            new CarFeature { Id = 156, CarId = 10, FeatureId = 5 },
            new CarFeature { Id = 157, CarId = 10, FeatureId = 6 },
            new CarFeature { Id = 158, CarId = 10, FeatureId = 7 },
            new CarFeature { Id = 159, CarId = 10, FeatureId = 9 },
            new CarFeature { Id = 160, CarId = 10, FeatureId = 17 },
            new CarFeature { Id = 161, CarId = 10, FeatureId = 19 },
            new CarFeature { Id = 162, CarId = 10, FeatureId = 20 },
            new CarFeature { Id = 163, CarId = 10, FeatureId = 23 },
            new CarFeature { Id = 164, CarId = 10, FeatureId = 28 },
            new CarFeature { Id = 165, CarId = 10, FeatureId = 30 },
            new CarFeature { Id = 166, CarId = 10, FeatureId = 40 },
            new CarFeature { Id = 167, CarId = 10, FeatureId = 41 },
            new CarFeature { Id = 168, CarId = 10, FeatureId = 45 },
            new CarFeature { Id = 169, CarId = 10, FeatureId = 36 },
            new CarFeature { Id = 170, CarId = 10, FeatureId = 48 },

            new CarFeature { Id = 171, CarId = 11, FeatureId = 1 },
            new CarFeature { Id = 172, CarId = 11, FeatureId = 3 },
            new CarFeature { Id = 173, CarId = 11, FeatureId = 5 },
            new CarFeature { Id = 174, CarId = 11, FeatureId = 6 },
            new CarFeature { Id = 175, CarId = 11, FeatureId = 7 },
            new CarFeature { Id = 176, CarId = 11, FeatureId = 9 },
            new CarFeature { Id = 177, CarId = 11, FeatureId = 17 },
            new CarFeature { Id = 178, CarId = 11, FeatureId = 19 },
            new CarFeature { Id = 179, CarId = 11, FeatureId = 20 },
            new CarFeature { Id = 180, CarId = 11, FeatureId = 21 },
            new CarFeature { Id = 181, CarId = 11, FeatureId = 23 },
            new CarFeature { Id = 182, CarId = 11, FeatureId = 28 },
            new CarFeature { Id = 183, CarId = 11, FeatureId = 30 },
            new CarFeature { Id = 184, CarId = 11, FeatureId = 31 },
            new CarFeature { Id = 185, CarId = 11, FeatureId = 34 },
            new CarFeature { Id = 186, CarId = 11, FeatureId = 40 },
            new CarFeature { Id = 187, CarId = 11, FeatureId = 41 },
            new CarFeature { Id = 188, CarId = 11, FeatureId = 45 },
            new CarFeature { Id = 189, CarId = 11, FeatureId = 47 },
            new CarFeature { Id = 190, CarId = 11, FeatureId = 48 },

            new CarFeature { Id = 191, CarId = 12, FeatureId = 1 },
            new CarFeature { Id = 192, CarId = 12, FeatureId = 3 },
            new CarFeature { Id = 193, CarId = 12, FeatureId = 5 },
            new CarFeature { Id = 194, CarId = 12, FeatureId = 6 },
            new CarFeature { Id = 195, CarId = 12, FeatureId = 7 },
            new CarFeature { Id = 196, CarId = 12, FeatureId = 9 },
            new CarFeature { Id = 197, CarId = 12, FeatureId = 17 },
            new CarFeature { Id = 198, CarId = 12, FeatureId = 19 },
            new CarFeature { Id = 199, CarId = 12, FeatureId = 20 },
            new CarFeature { Id = 200, CarId = 12, FeatureId = 21 },
            new CarFeature { Id = 201, CarId = 12, FeatureId = 23 },
            new CarFeature { Id = 202, CarId = 12, FeatureId = 28 },
            new CarFeature { Id = 203, CarId = 12, FeatureId = 30 },
            new CarFeature { Id = 204, CarId = 12, FeatureId = 31 },
            new CarFeature { Id = 205, CarId = 12, FeatureId = 34 },
            new CarFeature { Id = 206, CarId = 12, FeatureId = 40 },
            new CarFeature { Id = 207, CarId = 12, FeatureId = 41 },
            new CarFeature { Id = 208, CarId = 12, FeatureId = 45 },
            new CarFeature { Id = 209, CarId = 12, FeatureId = 47 },
            new CarFeature { Id = 210, CarId = 12, FeatureId = 48 },

            new CarFeature { Id = 211, CarId = 13, FeatureId = 1 },
            new CarFeature { Id = 212, CarId = 13, FeatureId = 3 },
            new CarFeature { Id = 213, CarId = 13, FeatureId = 5 },
            new CarFeature { Id = 214, CarId = 13, FeatureId = 6 },
            new CarFeature { Id = 215, CarId = 13, FeatureId = 7 },
            new CarFeature { Id = 216, CarId = 13, FeatureId = 9 },
            new CarFeature { Id = 217, CarId = 13, FeatureId = 17 },
            new CarFeature { Id = 218, CarId = 13, FeatureId = 19 },
            new CarFeature { Id = 219, CarId = 13, FeatureId = 20 },
            new CarFeature { Id = 220, CarId = 13, FeatureId = 21 },
            new CarFeature { Id = 221, CarId = 13, FeatureId = 23 },
            new CarFeature { Id = 222, CarId = 13, FeatureId = 28 },
            new CarFeature { Id = 223, CarId = 13, FeatureId = 30 },
            new CarFeature { Id = 224, CarId = 13, FeatureId = 31 },
            new CarFeature { Id = 225, CarId = 13, FeatureId = 34 },
            new CarFeature { Id = 226, CarId = 13, FeatureId = 40 },
            new CarFeature { Id = 227, CarId = 13, FeatureId = 41 },
            new CarFeature { Id = 228, CarId = 13, FeatureId = 45 },
            new CarFeature { Id = 229, CarId = 13, FeatureId = 47 },
            new CarFeature { Id = 230, CarId = 13, FeatureId = 48 },

            new CarFeature { Id = 231, CarId = 14, FeatureId = 1 },
            new CarFeature { Id = 232, CarId = 14, FeatureId = 3 },
            new CarFeature { Id = 233, CarId = 14, FeatureId = 5 },
            new CarFeature { Id = 234, CarId = 14, FeatureId = 6 },
            new CarFeature { Id = 235, CarId = 14, FeatureId = 7 },
            new CarFeature { Id = 236, CarId = 14, FeatureId = 9 },
            new CarFeature { Id = 237, CarId = 14, FeatureId = 17 },
            new CarFeature { Id = 238, CarId = 14, FeatureId = 19 },
            new CarFeature { Id = 239, CarId = 14, FeatureId = 20 },
            new CarFeature { Id = 240, CarId = 14, FeatureId = 21 },
            new CarFeature { Id = 241, CarId = 14, FeatureId = 23 },
            new CarFeature { Id = 242, CarId = 14, FeatureId = 28 },
            new CarFeature { Id = 243, CarId = 14, FeatureId = 30 },
            new CarFeature { Id = 244, CarId = 14, FeatureId = 31 },
            new CarFeature { Id = 245, CarId = 14, FeatureId = 34 },
            new CarFeature { Id = 246, CarId = 14, FeatureId = 40 },
            new CarFeature { Id = 247, CarId = 14, FeatureId = 41 },
            new CarFeature { Id = 248, CarId = 14, FeatureId = 45 },
            new CarFeature { Id = 249, CarId = 14, FeatureId = 47 },
            new CarFeature { Id = 250, CarId = 14, FeatureId = 48 },
            new CarFeature { Id = 251, CarId = 14, FeatureId = 36 },
            new CarFeature { Id = 252, CarId = 14, FeatureId = 46 },
            new CarFeature { Id = 253, CarId = 14, FeatureId = 42 },
            new CarFeature { Id = 254, CarId = 14, FeatureId = 43 },
            new CarFeature { Id = 255, CarId = 14, FeatureId = 44 },
            new CarFeature { Id = 256, CarId = 14, FeatureId = 49 },
            new CarFeature { Id = 257, CarId = 14, FeatureId = 50 },

            new CarFeature { Id = 258, CarId = 15, FeatureId = 1 },
            new CarFeature { Id = 259, CarId = 15, FeatureId = 5 },
            new CarFeature { Id = 260, CarId = 15, FeatureId = 6 },
            new CarFeature { Id = 261, CarId = 15, FeatureId = 7 },
            new CarFeature { Id = 262, CarId = 15, FeatureId = 9 },
            new CarFeature { Id = 263, CarId = 15, FeatureId = 17 },
            new CarFeature { Id = 264, CarId = 15, FeatureId = 19 },
            new CarFeature { Id = 265, CarId = 15, FeatureId = 23 },
            new CarFeature { Id = 266, CarId = 15, FeatureId = 30 },
            new CarFeature { Id = 267, CarId = 15, FeatureId = 40 },

            new CarFeature { Id = 268, CarId = 16, FeatureId = 1 },
            new CarFeature { Id = 269, CarId = 16, FeatureId = 3 },
            new CarFeature { Id = 270, CarId = 16, FeatureId = 5 },
            new CarFeature { Id = 271, CarId = 16, FeatureId = 6 },
            new CarFeature { Id = 272, CarId = 16, FeatureId = 7 },
            new CarFeature { Id = 273, CarId = 16, FeatureId = 9 },
            new CarFeature { Id = 274, CarId = 16, FeatureId = 17 },
            new CarFeature { Id = 275, CarId = 16, FeatureId = 19 },
            new CarFeature { Id = 276, CarId = 16, FeatureId = 20 },
            new CarFeature { Id = 277, CarId = 16, FeatureId = 21 },
            new CarFeature { Id = 278, CarId = 16, FeatureId = 23 },
            new CarFeature { Id = 279, CarId = 16, FeatureId = 28 },
            new CarFeature { Id = 280, CarId = 16, FeatureId = 30 },
            new CarFeature { Id = 281, CarId = 16, FeatureId = 31 },
            new CarFeature { Id = 282, CarId = 16, FeatureId = 34 },
            new CarFeature { Id = 283, CarId = 16, FeatureId = 40 },
            new CarFeature { Id = 284, CarId = 16, FeatureId = 41 },
            new CarFeature { Id = 285, CarId = 16, FeatureId = 45 },
            new CarFeature { Id = 286, CarId = 16, FeatureId = 47 },
            new CarFeature { Id = 287, CarId = 16, FeatureId = 48 },
            new CarFeature { Id = 288, CarId = 16, FeatureId = 36 },
            new CarFeature { Id = 289, CarId = 16, FeatureId = 46 },
            new CarFeature { Id = 290, CarId = 16, FeatureId = 42 },
            new CarFeature { Id = 291, CarId = 16, FeatureId = 43 },
            new CarFeature { Id = 292, CarId = 16, FeatureId = 44 },
            new CarFeature { Id = 293, CarId = 16, FeatureId = 49 },
            new CarFeature { Id = 294, CarId = 16, FeatureId = 50 },

            new CarFeature { Id = 295, CarId = 17, FeatureId = 1 },
            new CarFeature { Id = 296, CarId = 17, FeatureId = 3 },
            new CarFeature { Id = 297, CarId = 17, FeatureId = 5 },
            new CarFeature { Id = 298, CarId = 17, FeatureId = 6 },
            new CarFeature { Id = 299, CarId = 17, FeatureId = 7 },
            new CarFeature { Id = 300, CarId = 17, FeatureId = 9 },
            new CarFeature { Id = 301, CarId = 17, FeatureId = 17 },
            new CarFeature { Id = 302, CarId = 17, FeatureId = 19 },
            new CarFeature { Id = 303, CarId = 17, FeatureId = 20 },
            new CarFeature { Id = 304, CarId = 17, FeatureId = 21 },
            new CarFeature { Id = 305, CarId = 17, FeatureId = 23 },
            new CarFeature { Id = 306, CarId = 17, FeatureId = 28 },
            new CarFeature { Id = 307, CarId = 17, FeatureId = 30 },
            new CarFeature { Id = 308, CarId = 17, FeatureId = 31 },
            new CarFeature { Id = 309, CarId = 17, FeatureId = 34 },
            new CarFeature { Id = 310, CarId = 17, FeatureId = 40 },
            new CarFeature { Id = 311, CarId = 17, FeatureId = 41 },

            new CarFeature { Id = 312, CarId = 18, FeatureId = 1 },
            new CarFeature { Id = 313, CarId = 18, FeatureId = 3 },
            new CarFeature { Id = 314, CarId = 18, FeatureId = 5 },
            new CarFeature { Id = 315, CarId = 18, FeatureId = 6 },
            new CarFeature { Id = 316, CarId = 18, FeatureId = 7 },
            new CarFeature { Id = 317, CarId = 18, FeatureId = 9 },
            new CarFeature { Id = 318, CarId = 18, FeatureId = 17 },
            new CarFeature { Id = 319, CarId = 18, FeatureId = 19 },
            new CarFeature { Id = 320, CarId = 18, FeatureId = 20 },
            new CarFeature { Id = 321, CarId = 18, FeatureId = 21 },
            new CarFeature { Id = 322, CarId = 18, FeatureId = 23 },
            new CarFeature { Id = 323, CarId = 18, FeatureId = 28 },
            new CarFeature { Id = 324, CarId = 18, FeatureId = 30 },
            new CarFeature { Id = 325, CarId = 18, FeatureId = 31 },
            new CarFeature { Id = 326, CarId = 18, FeatureId = 34 },
            new CarFeature { Id = 327, CarId = 18, FeatureId = 40 },
            new CarFeature { Id = 328, CarId = 18, FeatureId = 41 },
            new CarFeature { Id = 329, CarId = 18, FeatureId = 45 },
            new CarFeature { Id = 330, CarId = 18, FeatureId = 47 },

            new CarFeature { Id = 331, CarId = 19, FeatureId = 1 },
            new CarFeature { Id = 332, CarId = 19, FeatureId = 5 },
            new CarFeature { Id = 333, CarId = 19, FeatureId = 6 },
            new CarFeature { Id = 334, CarId = 19, FeatureId = 7 },
            new CarFeature { Id = 335, CarId = 19, FeatureId = 9 },
            new CarFeature { Id = 336, CarId = 19, FeatureId = 17 },

            new CarFeature { Id = 337, CarId = 20, FeatureId = 1 },
            new CarFeature { Id = 338, CarId = 20, FeatureId = 5 },
            new CarFeature { Id = 339, CarId = 20, FeatureId = 6 },
            new CarFeature { Id = 340, CarId = 20, FeatureId = 7 },
            new CarFeature { Id = 341, CarId = 20, FeatureId = 9 },
            new CarFeature { Id = 342, CarId = 20, FeatureId = 17 },
            new CarFeature { Id = 343, CarId = 20, FeatureId = 19 },
            new CarFeature { Id = 344, CarId = 20, FeatureId = 23 },
            new CarFeature { Id = 345, CarId = 20, FeatureId = 30 },

            new CarFeature { Id = 346, CarId = 21, FeatureId = 1 },
            new CarFeature { Id = 347, CarId = 21, FeatureId = 3 },
            new CarFeature { Id = 348, CarId = 21, FeatureId = 5 },
            new CarFeature { Id = 349, CarId = 21, FeatureId = 6 },
            new CarFeature { Id = 350, CarId = 21, FeatureId = 7 },
            new CarFeature { Id = 351, CarId = 21, FeatureId = 9 },
            new CarFeature { Id = 352, CarId = 21, FeatureId = 17 },
            new CarFeature { Id = 353, CarId = 21, FeatureId = 19 },
            new CarFeature { Id = 354, CarId = 21, FeatureId = 20 },
            new CarFeature { Id = 355, CarId = 21, FeatureId = 21 },
            new CarFeature { Id = 356, CarId = 21, FeatureId = 23 },
            new CarFeature { Id = 357, CarId = 21, FeatureId = 28 },
            new CarFeature { Id = 358, CarId = 21, FeatureId = 30 },
            new CarFeature { Id = 359, CarId = 21, FeatureId = 31 },
            new CarFeature { Id = 360, CarId = 21, FeatureId = 34 },
            new CarFeature { Id = 361, CarId = 21, FeatureId = 40 },
            new CarFeature { Id = 362, CarId = 21, FeatureId = 41 },
            new CarFeature { Id = 363, CarId = 21, FeatureId = 45 },
            new CarFeature { Id = 364, CarId = 21, FeatureId = 47 },
            new CarFeature { Id = 365, CarId = 21, FeatureId = 48 },
            new CarFeature { Id = 366, CarId = 21, FeatureId = 36 },
            new CarFeature { Id = 367, CarId = 21, FeatureId = 46 },
            new CarFeature { Id = 368, CarId = 21, FeatureId = 42 },
            new CarFeature { Id = 369, CarId = 21, FeatureId = 43 },
            new CarFeature { Id = 370, CarId = 21, FeatureId = 44 },
            new CarFeature { Id = 371, CarId = 21, FeatureId = 49 },
            new CarFeature { Id = 372, CarId = 21, FeatureId = 50 },
            new CarFeature { Id = 373, CarId = 21, FeatureId = 25 },


            new CarFeature { Id = 374, CarId = 22, FeatureId = 1 },
            new CarFeature { Id = 375, CarId = 22, FeatureId = 3 },
            new CarFeature { Id = 376, CarId = 22, FeatureId = 5 },
            new CarFeature { Id = 377, CarId = 22, FeatureId = 6 },
            new CarFeature { Id = 378, CarId = 22, FeatureId = 7 },
            new CarFeature { Id = 379, CarId = 22, FeatureId = 9 },
            new CarFeature { Id = 380, CarId = 22, FeatureId = 17 },
            new CarFeature { Id = 381, CarId = 22, FeatureId = 19 },
            new CarFeature { Id = 382, CarId = 22, FeatureId = 23 },
            new CarFeature { Id = 383, CarId = 22, FeatureId = 28 }
            );
            modelBuilder.Entity<CType>().HasData(
     new CType { Id = 1, Name = "Sedan", SeatCapacity = 4 },
     new CType { Id = 2, Name = "SUV", SeatCapacity = 5 },
     new CType { Id = 3, Name = "SUV", SeatCapacity = 7 },
     new CType { Id = 4, Name = "Hatchback", SeatCapacity = 4 },
     new CType { Id = 5, Name = "Coupe", SeatCapacity = 2 },
     new CType { Id = 6, Name = "Grand Coupe", SeatCapacity = 4 },
     new CType { Id = 7, Name = "Convertible", SeatCapacity = 2 },
     new CType { Id = 8, Name = "Convertible", SeatCapacity = 4 },
     new CType { Id = 9, Name = "Minivan", SeatCapacity = 7 },
     new CType { Id = 10, Name = "Pickup", SeatCapacity = 2 },
     new CType { Id = 11, Name = "Pickup", SeatCapacity = 4 },
     new CType { Id = 12, Name = "Wagon", SeatCapacity = 5 }

 );
            modelBuilder.Entity<CarType>().HasData(
                new CarType { Id = 1, CarId = 1, TypeId = 1 },
                new CarType { Id = 2, CarId = 2, TypeId = 1 },
                new CarType { Id = 3, CarId = 3, TypeId = 6 },
                new CarType { Id = 4, CarId = 3, TypeId = 8 },
                new CarType { Id = 5, CarId = 4, TypeId = 6 },
                new CarType { Id = 6, CarId = 4, TypeId = 8 },
                new CarType { Id = 7, CarId = 5, TypeId = 6 },
                new CarType { Id = 8, CarId = 5, TypeId = 8 },
                new CarType { Id = 9, CarId = 6, TypeId = 5 },
                new CarType { Id = 10, CarId = 6, TypeId = 7 },
                new CarType { Id = 11, CarId = 7, TypeId = 5 },
                new CarType { Id = 12, CarId = 7, TypeId = 7 },
                new CarType { Id = 13, CarId = 8, TypeId = 5 },
                new CarType { Id = 14, CarId = 9, TypeId = 1 },
                new CarType { Id = 15, CarId = 10, TypeId = 5 },
                new CarType { Id = 16, CarId = 10, TypeId = 7 },
                new CarType { Id = 17, CarId = 11, TypeId = 1 },
                new CarType { Id = 18, CarId = 12, TypeId = 6 },
                new CarType { Id = 19, CarId = 12, TypeId = 8 },
                new CarType { Id = 20, CarId = 13, TypeId = 5 },
                new CarType { Id = 21, CarId = 14, TypeId = 2 },
                new CarType { Id = 22, CarId = 15, TypeId = 3 },
                new CarType { Id = 23, CarId = 16, TypeId = 5 },
                new CarType { Id = 24, CarId = 17, TypeId = 2 },
                new CarType { Id = 25, CarId = 18, TypeId = 6 },
                new CarType { Id = 26, CarId = 18, TypeId = 8 },
                new CarType { Id = 27, CarId = 19, TypeId = 1 },
                new CarType { Id = 28, CarId = 20, TypeId = 11 },
                new CarType { Id = 29, CarId = 21, TypeId = 2 },
                new CarType { Id = 30, CarId = 22, TypeId = 5 }
                );
            /* modelBuilder.Entity<Reservation>().HasData(
                 new Reservation { Id=1,StartDate="",EndDate="",}
             );*/




            base.OnModelCreating(modelBuilder);
        }
    }
}
