using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RentACar.DataAccess
{
    public class RentACarDbContext:IdentityDbContext<IdentityUser>
    {
        public RentACarDbContext(DbContextOptions<RentACarDbContext> options) : base(options) { }   
        public DbSet<Car> Cars { get; set; }
        public DbSet<CType> Types { get; set; }
        public DbSet<CarType> CarsTypes { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<CarFeature> CarsFeatures { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer>Customers { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>().HasData(
new Category { Id = 1, Name = "Economy" },
new Category { Id = 2, Name = "Luxury" },
new Category { Id = 3, Name = "Sport" },
new Category { Id = 4, Name = "German Cars" },
new Category { Id = 5, Name = "Electric" },
new Category { Id = 6, Name = "SUV" },
new Category { Id = 7, Name = "Muscle Cars" },
new Category { Id = 8, Name = "JDM Cars" },
new Category { Id = 9, Name = "Compact" },
new Category { Id = 10, Name = "Classic" }
);
            modelBuilder.Entity<Car>().HasData(
          new Car { Id = 1, Brand = "Toyota", Model = "Corolla", Gearbox = "Automatic", Year = 2021, PricePerDay = 80, PricePerWeek = 450, MileageLimitForDay = 150, MileageLimitForWeek = 1000, AdditionalMileageCharge = 0.2, EngineCapacity = 1.8, Color = "White", Available = true, Description = "Compact and fuel-efficient", CategoryId = 9 },
          new Car { Id = 2, Brand = "Honda", Model = "Civic", Gearbox = "Manual", Year = 2022, PricePerDay = 140, PricePerWeek = 600, MileageLimitForDay = 200, MileageLimitForWeek = 1200, AdditionalMileageCharge = 0.25, EngineCapacity = 2.0, Color = "Black", Available = true, Description = "Sporty and reliable", CategoryId = 3 },
          new Car { Id = 3, Brand = "Ford", Model = "Mustang", Gearbox = "Automatic", Year = 2020, PricePerDay = 200, PricePerWeek = 910, MileageLimitForDay = 250, MileageLimitForWeek = 1500, AdditionalMileageCharge = 0.22, EngineCapacity = 5.0, Color = "Black", Available = true, Description = "Comfortable and stylish", CategoryId = 7 },
          new Car { Id = 4, Brand = "BMW", Model = "420i", Gearbox = "Automatic", Year = 2022, PricePerDay = 250, PricePerWeek = 1000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 0.5, EngineCapacity = 0.0, Color = "Gray", Available = true, Description = "Luxury and performance", CategoryId = 2 },
          new Car { Id = 5, Brand = "Mercedes-Benz", Model = "C-Class", Gearbox = "Automatic", Year = 2021, PricePerDay = 210, PricePerWeek = 850, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 0.55, EngineCapacity = 3.0, Color = "Red", Available = true, Description = "Premium luxury", CategoryId = 2 },
          new Car { Id = 6, Brand = "Audi", Model = "R8 Spyder", Gearbox = "Automatic", Year = 2021, PricePerDay = 750, PricePerWeek = 6400, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 1.0, EngineCapacity = 5.2, Color = "Green", Available = true, Description = "High-performance sports car", CategoryId = 3 },
          new Car { Id = 7, Brand = "Lamborghini", Model = "Huracan", Gearbox = "Automatic", Year = 2023, PricePerDay = 1700, PricePerWeek = 9000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 1.5, EngineCapacity = 5.2, Color = "Black", Available = true, Description = "Exotic sports car", CategoryId = 3 },
          new Car { Id = 8, Brand = "Porsche", Model = "911 GT3", Gearbox = "Automatic", Year = 2023, PricePerDay = 1400, PricePerWeek = 8400, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 1.3, EngineCapacity = 4.0, Color = "Silver", Available = true, Description = "Luxury sports car", CategoryId = 2 },
          new Car { Id = 9, Brand = "Tesla", Model = "Model S Plaid", Gearbox = "Automatic", Year = 2023, PricePerDay = 350, PricePerWeek = 2100, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 1.0, EngineCapacity = 0.0, Color = "White", Available = true, Description = "Electric luxury sedan", CategoryId = 5 },
          new Car { Id = 10, Brand = "Ferrari", Model = "F8 Spider", Gearbox = "Automatic", Year = 2022, PricePerDay = 2300, PricePerWeek = 10000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 2.0, EngineCapacity = 3.9, Color = "Red", Available = true, Description = "Iconic Italian sports car", CategoryId = 3 },
          new Car { Id = 11, Brand = "Rolls-Royce", Model = "Phantom", Gearbox = "Automatic", Year = 2021, PricePerDay = 1000, PricePerWeek = 7000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 3.0, EngineCapacity = 6.7, Color = "Black", Available = true, Description = "Ultimate luxury car", CategoryId = 2 },
          new Car { Id = 12, Brand = "Bentley", Model = "Continental GT-GTC", Gearbox = "Automatic", Year = 2023, PricePerDay = 1300, PricePerWeek = 7600, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.5, EngineCapacity = 4.0, Color = "Black", Available = true, Description = "Grand luxury tourer", CategoryId = 2 },
          new Car { Id = 13, Brand = "McLaren", Model = "720S", Gearbox = "Automatic", Year = 2023, PricePerDay = 1700, PricePerWeek = 8000, MileageLimitForDay = 400, MileageLimitForWeek = 3000, AdditionalMileageCharge = 2.0, EngineCapacity = 4.0, Color = "Blue", Available = true, Description = "Exquisite British engineering", CategoryId = 3 },          
          new Car { Id = 14, Brand = "Aston Martin", Model = "DBX", Gearbox = "Automatic", Year = 2023, PricePerDay = 600, PricePerWeek = 3600, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 2.0, EngineCapacity = 4.0, Color = "Black", Available = true, Description = "Luxury British SUV", CategoryId = 6 },
          new Car { Id = 15, Brand = "Lexus", Model = "LX", Gearbox = "Automatic", Year = 2023, PricePerDay = 500, PricePerWeek = 3000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 3.4, Color = "Silver", Available = true, Description = "Sophisticated luxury SUV", CategoryId = 6 },
          new Car { Id = 16, Brand = "Mercedes-Benz", Model = "AMG GT", Gearbox = "Automatic", Year = 2022, PricePerDay = 2500, PricePerWeek = 1100, MileageLimitForDay = 400, MileageLimitForWeek = 2500, AdditionalMileageCharge = 2.2, EngineCapacity = 4.0, Color = "Orange", Available = true, Description = "German engineering excellence", CategoryId = 3 },
          new Car { Id = 17, Brand = "Audi", Model = "Q8", Gearbox = "Automatic", Year = 2021, PricePerDay = 400, PricePerWeek = 2300, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.0, EngineCapacity = 4.0, Color = "Orange", Available = true, Description = "Luxury SUV", CategoryId = 6 },
          new Car { Id = 18, Brand = "BMW", Model = "M4", Gearbox = "Automatic", Year = 2023, PricePerDay = 700, PricePerWeek = 4000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.5, EngineCapacity = 3.0, Color = "Yellow", Available = true, Description = "Sporty and agile", CategoryId = 3 },
          new Car { Id = 19, Brand = "Toyota", Model = "Camry", Gearbox = "Automatic", Year = 2021, PricePerDay = 130, PricePerWeek = 670, MileageLimitForDay = 200, MileageLimitForWeek = 1200, AdditionalMileageCharge = 0.25, EngineCapacity = 2.5, Color = "Red", Available = true, Description = "Dependable sedan", CategoryId = 9 },
          new Car { Id = 20, Brand = "Tesla", Model = "Cybertruck", Gearbox = "Automatic", Year = 2024, PricePerDay = 2000, PricePerWeek = 12000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 0.0, Color = "Black", Available = true, Description = "Sophisticated luxury SUV", CategoryId = 6 },
          new Car { Id = 21, Brand = "Land Rover", Model = "Range Rover", Gearbox = "Automatic", Year = 2023, PricePerDay = 1200, PricePerWeek = 7000, MileageLimitForDay = 300, MileageLimitForWeek = 2000, AdditionalMileageCharge = 1.8, EngineCapacity = 4.4, Color = "Black", Available = true, Description = "Sophisticated luxury SUV", CategoryId = 6 }

          );
            modelBuilder.Entity<Feature>().HasData(
      new Feature { Id = 1, NameOfFeatures = "Air Conditioning" },
      new Feature { Id = 2, NameOfFeatures = "Heated Seats" },
      new Feature { Id = 3, NameOfFeatures = "Bluetooth Connectivity" },
      new Feature { Id = 4, NameOfFeatures = "Navigation System" },
      new Feature { Id = 5, NameOfFeatures = "Cruise Control" },
      new Feature { Id = 6, NameOfFeatures = "Rearview Camera" },
      new Feature { Id = 7, NameOfFeatures = "Lane Departure Warning" },
      new Feature { Id = 8, NameOfFeatures = "Adaptive Headlights" },
      new Feature { Id = 9, NameOfFeatures = "Blind Spot Detection" },
      new Feature { Id = 10, NameOfFeatures = "Automatic Parking" },
      new Feature { Id = 11, NameOfFeatures = "Push-Button Start" },
      new Feature { Id = 12, NameOfFeatures = "Wireless Charging" },
      new Feature { Id = 13, NameOfFeatures = "Panoramic Sunroof" },
      new Feature { Id = 14, NameOfFeatures = "Power Adjustable Seats" },
      new Feature { Id = 15, NameOfFeatures = "Backup Sensors" },
      new Feature { Id = 16, NameOfFeatures = "Heated Steering Wheel" },
      new Feature { Id = 17, NameOfFeatures = "Keyless Entry" },
      new Feature { Id = 18, NameOfFeatures = "Surround-View Camera" },
      new Feature { Id = 19, NameOfFeatures = "Remote Start" },
      new Feature { Id = 20, NameOfFeatures = "Apple CarPlay" },
      new Feature { Id = 21, NameOfFeatures = "Android Auto" },
      new Feature { Id = 22, NameOfFeatures = "Rear Cross Traffic Alert" },
      new Feature { Id = 23, NameOfFeatures = "Adaptive Cruise Control" },
      new Feature { Id = 24, NameOfFeatures = "Heads-Up Display (HUD)" },
      new Feature { Id = 25, NameOfFeatures = "Ambient Lighting" },
      new Feature { Id = 26, NameOfFeatures = "Wireless Apple CarPlay" },
      new Feature { Id = 27, NameOfFeatures = "Power Tailgate" },
      new Feature { Id = 28, NameOfFeatures = "Automatic Emergency Braking" },
      new Feature { Id = 29, NameOfFeatures = "Traffic Sign Recognition" },
      new Feature { Id = 30, NameOfFeatures = "Rain-Sensing Wipers" },
      new Feature { Id = 31, NameOfFeatures = "Dual-Zone Climate Control" },
      new Feature { Id = 32, NameOfFeatures = "Power Folding Mirrors" },
      new Feature { Id = 33, NameOfFeatures = "Lane Keeping Assist" },
      new Feature { Id = 34, NameOfFeatures = "Electric Power Steering" },
      new Feature { Id = 35, NameOfFeatures = "Turbocharged Engine" },
      new Feature { Id = 36, NameOfFeatures = "Carbon Fiber Trim" },
      new Feature { Id = 37, NameOfFeatures = "Active Noise Cancellation" },
      new Feature { Id = 38, NameOfFeatures = "All-Wheel Drive" },
      new Feature { Id = 39, NameOfFeatures = "Front Parking Sensors" },
      new Feature { Id = 40, NameOfFeatures = "Sport Mode" },
      new Feature { Id = 41, NameOfFeatures = "Wireless Smartphone Charging" },
      new Feature { Id = 42, NameOfFeatures = "Massaging Seats" },
      new Feature { Id = 43, NameOfFeatures = "Self-Healing Paint" },
      new Feature { Id = 44, NameOfFeatures = "Night Vision" },
      new Feature { Id = 45, NameOfFeatures = "Active Rear Spoiler" },
      new Feature { Id = 46, NameOfFeatures = "Heads-Up Display with Navigation" },
      new Feature { Id = 47, NameOfFeatures = "Wireless Internet Access" },
      new Feature { Id = 48, NameOfFeatures = "Active Suspension" },
      new Feature { Id = 49, NameOfFeatures = "Power Adjustable Steering Wheel" },
      new Feature { Id = 50, NameOfFeatures = "Touchscreen Control Panel" }
  );

            modelBuilder.Entity<Image>().HasData(
                new Image { Id = 1,Url="/images/toyota-corolla1.jpg", CarId=1 },
                new Image { Id = 2, Url = "/images/toyota-corolla2.jpg", CarId = 1 },
                new Image { Id = 3, Url = "/images/toyota-corolla3.jpg", CarId = 1 },
                new Image { Id = 4, Url = "/images/toyota-corolla4.jpg", CarId = 1 },
                new Image { Id = 5, Url = "/images/honda-civic1.png", CarId = 2 },
                new Image { Id = 6, Url = "/images/honda-civic2.png", CarId = 2 },
                new Image { Id = 7, Url = "/images/honda-civic3.png", CarId = 2 },
                new Image { Id = 8, Url = "/images/honda-civic4.png", CarId = 2 },
                new Image { Id = 9, Url = "/images/bmw-420i1.png", CarId = 4 },
                new Image { Id = 10, Url = "/images/bmw-420i2.png", CarId = 4 },
                new Image { Id = 11, Url = "/images/bmw-420i7.png", CarId = 4 },
                new Image { Id = 12, Url = "/images/bmw-420i3.png", CarId = 4 },
                new Image { Id = 13, Url = "/images/bmw-420i4.png", CarId = 4 },
                new Image { Id = 14, Url = "/images/bmw-420i5.png", CarId = 4 },
                new Image { Id = 15, Url = "/images/bmw-420i6.png", CarId = 4 },
                new Image { Id = 16, Url = "/images/c300-1.webp", CarId = 5 },
                new Image { Id = 17, Url = "/images/c300-2.webp", CarId = 5 },
                new Image { Id = 18, Url = "/images/c300-3.webp", CarId = 5 },
                new Image { Id = 19, Url = "/images/c300-4.webp", CarId = 5 },
                new Image { Id = 20, Url = "/images/c300-5.webp", CarId = 5 },
                new Image { Id = 21, Url = "/images/c300-6.webp", CarId = 5 },
                new Image { Id = 22, Url = "/images/ford-mustang1.jpg", CarId = 3 },
                new Image { Id = 23, Url = "/images/ford-mustang2.jpg", CarId = 3 },
                new Image { Id = 24, Url = "/images/ford-mustang3.jpg", CarId = 3 },
                new Image { Id = 25, Url = "/images/ford-mustang4.jpg", CarId = 3 },
                new Image { Id = 26, Url = "/images/ford-mustang5.jpg", CarId = 3 },
                new Image { Id = 27, Url = "/images/ford-mustang6.jpg", CarId = 3 },
                new Image { Id = 28, Url = "/images/ford-mustang7.jpg", CarId = 3 },
                new Image { Id = 29, Url = "/images/ford-mustang8.jpg", CarId = 3 },
                new Image { Id = 30, Url = "/images/audi-r8-1.jpg", CarId = 6 },
                new Image { Id = 31, Url = "/images/audi-r8-2.jpg", CarId = 6 },
                new Image { Id = 32, Url = "/images/audi-r8-3.jpg", CarId = 6 },
                new Image { Id = 33, Url = "/images/audi-r8-4.jpg", CarId = 6 },
                new Image { Id = 34, Url = "/images/audi-r8-5.jpg", CarId = 6 },
                new Image { Id = 35, Url = "/images/audi-r8-6.jpg", CarId = 6 },
                new Image { Id = 36, Url = "/images/audi-r8-7.jpg", CarId = 6 },
                new Image { Id = 37, Url = "/images/audi-r8-8.jpg", CarId = 6 },
                new Image { Id = 38, Url = "/images/lambo-hur-1.jpg", CarId = 7 },
                new Image { Id = 39, Url = "/images/lambo-hur-2.jpg", CarId = 7 },
                new Image { Id = 40, Url = "/images/lambo-hur-3.jpg", CarId = 7 },
                new Image { Id = 41, Url = "/images/lambo-hur-4.jpg", CarId = 7 },
                new Image { Id = 42, Url = "/images/lambo-hur-5.jpg", CarId = 7 },
                new Image { Id = 43, Url = "/images/porsche-gt3-1.webp", CarId = 8 },
                new Image { Id = 44, Url = "/images/porsche-gt3-2.webp", CarId = 8 },
                new Image { Id = 45, Url = "/images/porsche-gt3-3.webp", CarId = 8 },
                new Image { Id = 46, Url = "/images/porsche-gt3-4.webp", CarId = 8 },
                new Image { Id = 47, Url = "/images/porsche-gt3-5.webp", CarId = 8 },
                new Image { Id = 48, Url = "/images/porsche-gt3-6.webp", CarId = 8 },
                new Image { Id = 49, Url = "/images/porsche-gt3-7.webp", CarId = 8 },
                new Image { Id = 50, Url = "/images/porsche-gt3-8.webp", CarId = 8 },
                new Image { Id = 51, Url = "/images/tesla-s-1.webp", CarId = 9 },
                new Image { Id = 52, Url = "/images/tesla-s-2.webp", CarId = 9 },
                new Image { Id = 53, Url = "/images/tesla-s-3.webp", CarId = 9 },
                new Image { Id = 54, Url = "/images/tesla-s-4.webp", CarId = 9 },
                new Image { Id = 55, Url = "/images/tesla-s-5.webp", CarId = 9 },
                new Image { Id = 56, Url = "/images/tesla-s-6.webp", CarId = 9 },
                new Image { Id = 57, Url = "/images/ferrari-f-1.webp", CarId = 10 },
                new Image { Id = 58, Url = "/images/ferrari-f-2.webp", CarId = 10 },
                new Image { Id = 59, Url = "/images/ferrari-f-3.webp", CarId = 10 },
                new Image { Id = 60, Url = "/images/ferrari-f-4.webp", CarId = 10 },
                new Image { Id = 61, Url = "/images/ferrari-f-5.webp", CarId = 10 },
                new Image { Id = 62, Url = "/images/ferrari-f-6.webp", CarId = 10 },
                new Image { Id = 63, Url = "/images/ferrari-f-7.webp", CarId = 10 },
                new Image { Id = 64, Url = "/images/ferrari-f-8.webp", CarId = 10 },
                new Image { Id = 65, Url = "/images/phanthom-1.webp", CarId = 11 },
                new Image { Id = 66, Url = "/images/phanthom-2.webp", CarId = 11 },
                new Image { Id = 67, Url = "/images/phanthom-3.webp", CarId = 11 },
                new Image { Id = 68, Url = "/images/phanthom-4.webp", CarId = 11 },
                new Image { Id = 69, Url = "/images/phanthom-5.webp", CarId = 11 },
                new Image { Id = 70, Url = "/images/phanthom-6.webp", CarId = 11 },
                new Image { Id = 71, Url = "/images/phanthom-7.webp", CarId = 11 },
                new Image { Id = 72, Url = "/images/phanthom-8.webp", CarId = 11 },
                new Image { Id = 73, Url = "/images/phanthom-9.webp", CarId = 11 },
                new Image { Id = 74, Url = "/images/phanthom-10.webp", CarId = 11 },
                new Image { Id = 75, Url = "/images/phanthom-11.webp", CarId = 11 },
                new Image { Id = 76, Url = "/images/bentley-continental-gt-1.webp", CarId = 12 },
                new Image { Id = 77, Url = "/images/bentley-continental-gt-2.webp", CarId = 12 },
                new Image { Id = 78, Url = "/images/bentley-continental-gt-3.webp", CarId = 12 },
                new Image { Id = 79, Url = "/images/bentley-continental-gt-4.webp", CarId = 12 },
                new Image { Id = 80, Url = "/images/bentley-continental-gt-5.webp", CarId = 12 },
                new Image { Id = 81, Url = "/images/bentley-continental-gt-6.webp", CarId = 12 },
                new Image { Id = 82, Url = "/images/bentley-continental-gt-7.webp", CarId = 12 },
                new Image { Id = 83, Url = "/images/bentley-continental-gt-8.webp", CarId = 12 },
                new Image { Id = 84, Url = "/images/bentley-continental-gt-9.webp", CarId = 12 },
                new Image { Id = 85, Url = "/images/bentley-continental-gt-10.webp", CarId = 12 },
                new Image { Id = 86, Url = "/images/bentley-continental-gt-11.webp", CarId = 12 },
                new Image { Id = 87, Url = "/images/bentley-continental-gt-12.webp", CarId = 12 },
                new Image { Id = 88, Url = "/images/mc-720s-1.webp", CarId = 13 },
                new Image { Id = 89, Url = "/images/mc-720s-2.webp", CarId = 13 },
                new Image { Id = 90, Url = "/images/mc-720s-3.webp", CarId = 13 },
                new Image { Id = 91, Url = "/images/mc-720s-4.webp", CarId = 13 },
                new Image { Id = 92, Url = "/images/mc-720s-5.webp", CarId = 13 },
                new Image { Id = 93, Url = "/images/mc-720s-6.webp", CarId = 13 },
                new Image { Id = 94, Url = "/images/mc-720s-7.webp", CarId = 13 },
                new Image { Id = 95, Url = "/images/aston-dbx-1.webp", CarId = 14 },
                new Image { Id = 96, Url = "/images/aston-dbx-2.webp", CarId = 14 },
                new Image { Id = 97, Url = "/images/aston-dbx-3.webp", CarId = 14 },
                new Image { Id = 98, Url = "/images/aston-dbx-4.webp", CarId = 14 },
                new Image { Id = 99, Url = "/images/aston-dbx-5.webp", CarId = 14 },
                new Image { Id = 100, Url = "/images/aston-dbx-6.webp", CarId = 14 },
                new Image { Id = 101, Url = "/images/aston-dbx-7.webp", CarId = 14 },
                new Image { Id = 102, Url = "/images/aston-dbx-8.webp", CarId = 14 },
                new Image { Id = 103, Url = "/images/lexus-lx-1.webp", CarId = 15 },
                new Image { Id = 104, Url = "/images/lexus-lx-2.webp", CarId = 15 },
                new Image { Id = 105, Url = "/images/lexus-lx-3.webp", CarId = 15 },
                new Image { Id = 106, Url = "/images/lexus-lx-4.webp", CarId = 15 },
                new Image { Id = 107, Url = "/images/lexus-lx-5.webp", CarId = 15 },
                new Image { Id = 108, Url = "/images/lexus-lx-6.webp", CarId = 15 },
                new Image { Id = 109, Url = "/images/lexus-lx-7.webp", CarId = 15 },
                new Image { Id = 110, Url = "/images/amg-gt-1.webp", CarId = 16 },
                new Image { Id = 111, Url = "/images/amg-gt-2.webp", CarId = 16 },
                new Image { Id = 112, Url = "/images/amg-gt-3.webp", CarId = 16 },
                new Image { Id = 113, Url = "/images/amg-gt-4.webp", CarId = 16 },
                new Image { Id = 114, Url = "/images/amg-gt-5.webp", CarId = 16 },
                new Image { Id = 115, Url = "/images/amg-gt-6.webp", CarId = 16 },
                new Image { Id = 116, Url = "/images/amg-gt-7.webp", CarId = 16 },
                new Image { Id = 117, Url = "/images/amg-gt-8.webp", CarId = 16 },
                new Image { Id = 118, Url = "/images/audi-q8-1.webp", CarId = 17 },
                new Image { Id = 119, Url = "/images/audi-q8-2.webp", CarId = 17 },
                new Image { Id = 120, Url = "/images/audi-q8-3.webp", CarId = 17 },
                new Image { Id = 121, Url = "/images/audi-q8-4.webp", CarId = 17 },
                new Image { Id = 122, Url = "/images/audi-q8-5.webp", CarId = 17 },
                new Image { Id = 123, Url = "/images/audi-q8-6.webp", CarId = 17 },
                new Image { Id = 124, Url = "/images/audi-q8-7.webp", CarId = 17 },
                new Image { Id = 125, Url = "/images/audi-q8-8.webp", CarId = 17 },
                new Image { Id = 126, Url = "/images/audi-q8-9.webp", CarId = 17 },
                new Image { Id = 127, Url = "/images/bmw-m4-1.webp", CarId = 18 },
                new Image { Id = 128, Url = "/images/bmw-m4-2.webp", CarId = 18 },
                new Image { Id = 129, Url = "/images/bmw-m4-3.webp", CarId = 18 },
                new Image { Id = 130, Url = "/images/bmw-m4-4.webp", CarId = 18 },
                new Image { Id = 131, Url = "/images/bmw-m4-5.webp", CarId = 18 },
                new Image { Id = 132, Url = "/images/bmw-m4-6.webp", CarId = 18 },
                new Image { Id = 133, Url = "/images/camry-1.webp", CarId = 19 },
                new Image { Id = 134, Url = "/images/camry-2.webp", CarId = 19 },
                new Image { Id = 135, Url = "/images/camry-3.webp", CarId = 19 },
                new Image { Id = 136, Url = "/images/camry-4.webp", CarId = 19 },
                new Image { Id = 137, Url = "/images/camry-5.webp", CarId = 19 },
                new Image { Id = 138, Url = "/images/camry-6.webp", CarId = 19 },
                new Image { Id = 139, Url = "/images/camry-7.webp", CarId = 19 },
                new Image { Id = 140, Url = "/images/cybertruck-1.webp", CarId = 20 },
                new Image { Id = 141, Url = "/images/cybertruck-2.webp", CarId = 20 },
                new Image { Id = 142, Url = "/images/cybertruck-3.webp", CarId = 20 },
                new Image { Id = 143, Url = "/images/cybertruck-4.webp", CarId = 20 },
                new Image { Id = 144, Url = "/images/cybertruck-5.webp", CarId = 20 },
                new Image { Id = 145, Url = "/images/rover-1.webp", CarId = 21 },
                new Image { Id = 146, Url = "/images/rover-2.webp", CarId = 21 },
                new Image { Id = 147, Url = "/images/rover-3.webp", CarId = 21 },
                new Image { Id = 148, Url = "/images/rover-4.webp", CarId = 21 },
                new Image { Id = 149, Url = "/images/rover-5.webp", CarId = 21 },
                new Image { Id = 150, Url = "/images/rover-6.webp", CarId = 21 },
                new Image { Id = 151, Url = "/images/rover-7.webp", CarId = 21 },
                new Image { Id = 152, Url = "/images/rover-8.webp", CarId = 12 },
                new Image { Id = 153, Url = "/images/rover-9.webp", CarId = 12 }
                );
            base.OnModelCreating(modelBuilder);
        }
    }
}
